// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Shared.StatusIcon;
using Content.Trauma.Client.Stylesheets.Sheetlets;
using Content.Trauma.Shared.SecTrack;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Trauma.Client.SecTrack;

[GenerateTypedNameReferences]
public sealed partial class SecTrackWindow : BaseWindow
{
    [Dependency] private IUserInterfaceManager _ui = default!;
    [Dependency] private IResourceCache _resCache = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IGameTiming _gameTiming = default!;
    private readonly ClientGameTicker _gameTicker;
    private readonly SpriteSystem _sprite;

    private string _station = Loc.GetString("sec-track-unknown");
    private Dictionary<string, SquadEntry> _squadEntries = new();
    private Dictionary<string, CrewMemberInfo> _lastCrewData = new();
    private Dictionary<NetEntity, TimerEntryControl> _timerControls = new();

    public Action<string>? OnCreateSquad;
    public Action<string, string>? OnRenameSquad;
    public Action<string>? OnDeleteSquad;
    public Action<string, string>? OnUpdateSquadDescription;
    public Action<string, SquadStatus>? OnChangeSquadStatus;
    public Action<string, string>? OnAddMemberToSquad;
    public Action<string, string>? OnRemoveMemberFromSquad;
    public Action<string, int>? OnChangeSquadIcon;
    public Action<NetEntity>? OnRemoveTimer;

    public SecTrackWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entitySystem.GetEntitySystem<SpriteSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();

        SetupAllStyles();

        CloseButton.OnPressed += _ => Close();

        NewSquadName.OnTextChanged += OnSquadNameTextChanged;

        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
        CreateSquadButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(NewSquadName.Text))
            {
                var squadName = FormattedMessage.RemoveMarkupOrThrow(NewSquadName.Text);
                if (squadName.Length > 16) squadName = squadName[..16];

                OnCreateSquad?.Invoke(squadName);
                NewSquadName.Text = string.Empty;
                CreateSquadButton.Disabled = true;
            }
        };
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        StationLabel.Text = Loc.GetString("sec-track-ui-mark", ("time", stationTime.ToString("hh\\:mm\\:ss")), ("station", _station));
    }

    private void SetupAllStyles()
    {
        Tabs.SetTabTitle(0, Loc.GetString("sec-track-tab-squads"));
        Tabs.SetTabTitle(1, Loc.GetString("sec-track-tab-timers"));
        Tabs.AddStyleClass(SecTrackSheetlet.StyleClassTabContainer);

        StationLabel.AddStyleClass(SecTrackSheetlet.StyleClassConsoleHeading);
        NewSquadName.AddStyleClass(SecTrackSheetlet.StyleClassConsoleLineEdit);
        CreateSquadButton.AddStyleClass(SecTrackSheetlet.StyleClassButtonRed);

        UnassignedCountLabel.AddStyleClass(SecTrackSheetlet.StyleClassConsoleSubTextOne);
        SquadsCountLabel.AddStyleClass(SecTrackSheetlet.StyleClassConsoleSubTextOne);
        Footer.AddStyleClass(SecTrackSheetlet.StyleClassConsoleSubTextTwo);
    }

    private void OnSquadNameTextChanged(LineEdit.LineEditEventArgs args)
    {
        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
    }

    public void UpdateState(SecTrackUpdateState state)
    {
        _station = state.StationName?.ToUpperInvariant() ?? Loc.GetString("sec-track-unknown");

        UpdateUnassignedList(state.UnassignedSecurity, state.Squads);
        UpdateSquadsList(state.Squads);
    }

    public void UpdateSensorStatuses(SensorStatusUpdateState sensorState)
    {
        foreach (var squadEntry in _squadEntries.Values)
        {
            squadEntry.UpdateSensorStatuses(sensorState.MemberStatuses, sensorState.SquadLocations);
        }
    }

    public void UpdateTimerState(TimerUpdateState state)
    {
        UpdateTimersList(state.Timers);
    }

    private void UpdateUnassignedList(List<CrewMemberInfo> unassigned, List<Squad> squads)
    {
        UnassignedCountLabel.Text = unassigned.Count.ToString();
        UnassignedContainer.Children.Clear();

        foreach (var member in unassigned)
        {
            SpriteSpecifier? iconSpecifier = null;
            if (_prototypeManager.HasIndex<JobIconPrototype>(member.JobIcon))
                iconSpecifier = _prototypeManager.Index<JobIconPrototype>(member.JobIcon).Icon;
            else if (_prototypeManager.HasIndex<StatusIconPrototype>(member.JobIcon))
                iconSpecifier = _prototypeManager.Index<StatusIconPrototype>(member.JobIcon).Icon;

            var entry = new CrewMemberEntry(member, squads, iconSpecifier, _sprite);
            entry.OnAssignPressed += squadId =>
                OnAddMemberToSquad?.Invoke(squadId, member.MemberId);
            UnassignedContainer.AddChild(entry);
        }
    }

    private void UpdateSquadsList(List<Squad> squads)
    {
        SquadsCountLabel.Text = squads.Count.ToString();
        SquadsContainer.Children.Clear();
        _squadEntries.Clear();

        foreach (var squad in squads)
        {
            var entry = new SquadEntry(squad, _prototypeManager, _sprite);
            entry.OnIconChanged += iconId =>
                OnChangeSquadIcon?.Invoke(squad.SquadId, iconId);
            entry.OnRenamePressed += newName =>
            {
                var cleanName = FormattedMessage.RemoveMarkupOrThrow(newName);
                if (cleanName.Length > 16) cleanName = cleanName[..16];

                OnRenameSquad?.Invoke(squad.SquadId, cleanName);
            };
            entry.OnDeletePressed += () =>
                OnDeleteSquad?.Invoke(squad.SquadId);
            entry.OnUpdateDescriptionPressed += description =>
                OnUpdateSquadDescription?.Invoke(squad.SquadId, description);
            entry.OnStatusChanged += status =>
                OnChangeSquadStatus?.Invoke(squad.SquadId, status);
            entry.OnRemoveMemberPressed += memberId =>
                OnRemoveMemberFromSquad?.Invoke(squad.SquadId, memberId);

            SquadsContainer.AddChild(entry);
            _squadEntries[squad.SquadId] = entry;

            foreach (var member in squad.Members)
            {
                _lastCrewData[member.MemberId] = member;
            }
        }
    }

    private void UpdateTimersList(List<TimerEntry> timers)
    {
        TimersCountLabel.Text = timers.Count.ToString();

        var toRemove = new List<NetEntity>();
        foreach (var (timerUid, control) in _timerControls)
        {
            if (!timers.Any(t => t.TimerUid == timerUid))
                toRemove.Add(timerUid);
        }

        foreach (var timerUid in toRemove)
        {
            if (_timerControls.TryGetValue(timerUid, out var control))
            {
                TimersContainer.Children.Remove(control);
                _timerControls.Remove(timerUid);
            }
        }

        foreach (var timer in timers)
        {
            if (!_timerControls.TryGetValue(timer.TimerUid, out var control))
            {
                control = new TimerEntryControl(timer);
                control.OnRemovePressed += () =>
                    OnRemoveTimer?.Invoke(timer.TimerUid);
                TimersContainer.AddChild(control);
                _timerControls[timer.TimerUid] = control;
            }
            else
            {
                control.UpdateTimer(timer);
            }
        }

        var sortedChildren = TimersContainer.Children
            .OfType<TimerEntryControl>()
            .OrderBy(t => t.RemainingTime.TotalSeconds)
            .ToList();

        TimersContainer.Children.Clear();
        foreach (var child in sortedChildren)
        {
            TimersContainer.AddChild(child);
        }
    }
}
