// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Client.SecTrack.Stylesheets;
using Content.Trauma.Client.Stylesheets.Sheetlets;
using Content.Trauma.Shared.SecTrack;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.SecTrack;

[GenerateTypedNameReferences]
public sealed partial class TimerEntryControl : PanelContainer
{
    private TimerEntry _timerEntry;

    public TimeSpan RemainingTime => _timerEntry.RemainingTime;

    public Action? OnRemovePressed;

    public TimerEntryControl(TimerEntry timerEntry)
    {
        RobustXamlLoader.Load(this);

        _timerEntry = timerEntry;

        RemoveButton.OnPressed += _ => OnRemovePressed?.Invoke();

        SetupStyles();
        UpdateDisplay();
    }

    private void SetupStyles()
    {
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#2a0a0a"),
            BorderColor = SecTrackSheetlet.TabActiveColor,
            BorderThickness = new Thickness(1),
            ContentMarginBottomOverride = 6,
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 6
        };

        RemoveButton.AddStyleClass(SecTrackSheetlet.StyleClassButtonRed);

        TimerLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerHeader);
        TimeLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerHeader);
        TotalTimeLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerText);
    }

    public void UpdateTimer(TimerEntry timerEntry)
    {
        _timerEntry = timerEntry;
        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        TimerLabel.Text = _timerEntry.Label;

        var remaining = _timerEntry.RemainingTime;
        UpdateTimeLabel(remaining);

        TotalTimeLabel.Text = FormatTimeSpan(_timerEntry.TotalTime);
    }

    private void UpdateTimeLabel(TimeSpan remaining)
    {
        TimeLabel.RemoveStyleClass(SecTrackSheetlet.StyleClassTimerNormal);
        TimeLabel.RemoveStyleClass(SecTrackSheetlet.StyleClassTimerWarning);
        TimeLabel.RemoveStyleClass(SecTrackSheetlet.StyleClassTimerCritical);
        TimeLabel.RemoveStyleClass(SecTrackSheetlet.StyleClassTimerOverdue);
        if (remaining < TimeSpan.Zero)
        {
            var overdue = -remaining;
            TimeLabel.Text = $"-{FormatTimeSpan(overdue)}";
            TimeLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerOverdue);
        }
        else
        {
            TimeLabel.Text = FormatTimeSpan(remaining);

            if (remaining.TotalSeconds < 30)
                TimeLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerCritical);
            else if (remaining.TotalSeconds < 60)
                TimeLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerWarning);
            else
                TimeLabel.AddStyleClass(SecTrackSheetlet.StyleClassTimerNormal);
        }
    }

    private string FormatTimeSpan(TimeSpan timeSpan)
    {
        if (timeSpan.TotalHours >= 1)
        {
            return $"{(int) timeSpan.TotalHours:00}:{timeSpan.Minutes:00}:{timeSpan.Seconds:00}";
        }
        else
        {
            return $"{timeSpan.Minutes:00}:{timeSpan.Seconds:00}";
        }
    }
}
