// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.SpeechPro;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.SpeechPro.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeechProUiFragment : BoxContainer
{
    private const float TwoColumnWidth = 360f;
    private const float FourColumnWidth = 560f;
    private int _columns = 3;

    public event Action<byte>? OnPhraseSelected;

    public SpeechProUiFragment()
    {
        RobustXamlLoader.Load(this);

        for (var i = 0; i < SpeechProPhrases.All.Count; i++)
        {
            AddButton((byte) i, SpeechProPhrases.All[i]);
        }
    }

    private void AddButton(byte index, SpeechProPhrase phrase)
    {
        var button = new Button
        {
            Text = Loc.GetString(phrase.ButtonLocId),
            ClipText = true,
            HorizontalExpand = true,
            Margin = new Thickness(1),
            MinHeight = 28,
        };

        button.OnPressed += _ => OnPhraseSelected?.Invoke(index);
        GetGrid(phrase.Section).AddChild(button);
    }

    private GridContainer GetGrid(SpeechProPhraseSection section)
    {
        return section switch
        {
            SpeechProPhraseSection.Basic => BasicGrid,
            SpeechProPhraseSection.Needs => NeedsGrid,
            SpeechProPhraseSection.Tourism => TourismGrid,
            SpeechProPhraseSection.Alerts => AlertsGrid,
            _ => BasicGrid,
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var columns = Size.X switch
        {
            < TwoColumnWidth => 2,
            >= FourColumnWidth => 4,
            _ => 3,
        };

        if (_columns == columns)
            return;

        _columns = columns;
        BasicGrid.Columns = columns;
        NeedsGrid.Columns = columns;
        TourismGrid.Columns = columns;
        AlertsGrid.Columns = columns;
    }
}
