// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.SpeechPro.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeechProWindow : DefaultWindow
{
    public event Action<byte>? OnPhraseSelected;

    public SpeechProWindow()
    {
        RobustXamlLoader.Load(this);

        SpeechProFragment.OnPhraseSelected += phrase => OnPhraseSelected?.Invoke(phrase);
    }
}
