// <Trauma>
using Content.Shared.FixedPoint;
// </Trauma>
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineItem : BoxContainer
{
    public VendingMachineItem(EntProtoId entProto, string text, FixedPoint2 price) // Trauma - money
    {
        RobustXamlLoader.Load(this);

        ItemPrototype.SetPrototype(entProto);

        NameLabel.Text = text;
        SetPrice(price); // Trauma - money
    }

    public void SetText(string text)
    {
        NameLabel.Text = text;
    }

    // <Trauma>
    public void SetPrice(FixedPoint2 price)
    {
        PriceLabel.Text = $"${price}";
    }
    // </Trauma>
}
