<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Content.Goobstation.Maths</RootNamespace>
    </PropertyGroup>
    <Import Project="../MSBuild/Content.props" />

    <ItemGroup>
      <ProjectReference Include="..\Content.ModuleManager\Content.ModuleManager.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Materials\MaterialComponent.cs">
        <SubType>Component</SubType>
      </Compile>
    </ItemGroup>

    <Import Project="../RobustToolbox/Imports/Shared.props" />
    <Import Project="../RobustToolbox/MSBuild/Robust.Properties.targets" />
</Project>
