# TraumaStation's pre-commit.com config  
# You don't have to install it yourself, CI applies fixes to PRs automatically (but it's still good to have)
# Use `pip3 install pre-commit` or use your system package.

# don't touch upstream files
files: "_Trauma"
repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v6.0.0"
  hooks:
  # File checkers
  - id: check-yaml
    # only check prototypes, maps would be too slow
    files: "^Resources/Prototypes/_Trauma/.*\\.yml$"
    # !type:... doesn't work without somehow loading SS14, which would probably make commits take years
    args: ["--unsafe"]
  - id: check-json
    # only need to check meta.json files
    files: "^Resources/Textures/_Trauma/.*/meta\\.json$"
  - id: check-xml
    # Check all ui XAML files
    # Can't check guidebook "xml" as it is a monster
    files: "^Content.Trauma.Client/.*\\.xaml$"
    types: ["text"]
  - id: check-merge-conflict
  # Fixers that can and will change commits to PRs
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-byte-order-marker
