- type: entity
  id: BaseTalent
  abstract: true
  components:
  - type: Talent

- type: entity
  parent: BaseTalent
  id: DamageBonusTalent
  name: Damage Talent
  description: Hit harder.
  components:
  - type: DamageTalent

- type: entity
  parent: BaseTalent
  id: SpeedTalent
  name: Speed Talent
  description: You want to hit things faster? Look no further!
  components:
  - type: SpeedTalent

- type: entity
  parent: BaseTalent
  id: DodgeTalent
  name: Dodge Talent
  description: You want to dodge things? Look no further!
  components:
  - type: Dodge

- type: entity
  parent: BaseTalent
  id: FastHealerTalent
  name: Fast Healer
  description: Heal faster. Twice as fast.
  components:
  - type: FastHealer

- type: entity
  parent: BaseTalent
  id: PoisonResistantTalent
  name: Poison Resistance
  description: Resist all chems!
  components:
  - type: Talent
    repeat: true
  - type: PoisonResistant

- type: entity
  parent: BaseTalent
  id: StoutTalent
  name: Stout
  description: Get knocked down less.
  components:
  - type: Stout

- type: entity
  parent: BaseTalent
  id: ToughHideTalent
  name: Tough Hide
  description: You want to not die? Look no further. The tougher your hide, the less damage you'll take.
  components:
  - type: Talent
    repeat: true
  - type: ToughHide
