- type: chameleonOutfit
  id: BrigmedicChameleonOutfit
  job: Brigmedic
  equipment:
    eyes: ClothingEyesGlassesMed
    mask: ClothingMaskBreathMedicalSecurity
    ears: ClothingHeadsetBrigmedic
    outerClothing: ClothingOuterCoatAMG
    gloves: ClothingHandsGlovesColorWhite
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    id: BrigmedicPDA
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatBeretBrigmedic
