- type: startingGear
  id: CentcomInsiderAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    back: ClothingBackpackSatchelLeatherFilledAgent
    shoes: ClothingShoesChameleonNoSlips
    mask: ClothingMaskGasChameleon
    outerClothing: ClothingOuterArmorInvisibleChameleon
    eyes: ClothingEyesGlassesDeathsquad # The calm before the storm.
    gloves: ClothingAdmemeHandsChameleonInsulated # Certified NT stolen-and-improved Syndicate technology.
    id: ChameleonAgentPDA
    ears: ClothingHeadsetChamleon
    belt: BoxFolderClipboardThreePapers # For potential roleplay/notes taking.
    pocket1: WeaponDisablerAdvanced
    pocket2: TelescopicBatonAdvanced
  inhand:
  - VoiceMaskImplanter # Captured Syndicate technology, shamelessly used by top execs.
  - ChameleonControllerImplanter
