- type: startingGear
  id: CentcomFormalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    back: ClothingBackpackSatchelHoldingCentcomFormalFilled
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    neck: ExecutiveIDCard # This is effectively an access breaker. Keep that in mind when making custom loadouts with it.
    eyes: ClothingEyesGlassesCentCommNoThermal # Actually fits better with the loadout and was clearly designed for this purpose. Appears equivalent to medsec.
    gloves: ClothingHandsGlovesCombat
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    belt: BoxFolderCentComClipboardThreePapers
    pocket1: WeaponDisablerAdvanced
    pocket2: WeaponRevolverMateba
  inhand:
  - CentcommMindShieldImplanter
  - DeathRattleImplanterCentcomm

- type: startingGear
  id: CentcomInspectorGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcomFormalDress
    shoes: ClothingShoesBootsJackFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    gloves: ClothingHandsGlovesCombat
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    pocket1: WeaponDisablerAdvanced
    pocket2: FlashlightSeclite
    suitstorage: OxygenTankFilled
  inhand:
  - BriefcaseCentcomInspector
- type: startingGear
# This loadout is meant for very specific circumstances, or if the relevant character will remain on CentComm.
# Due to the items inside, any character ON STATION with this loadout should have ERT Sec guards.
# Example usage: In-character investigations ordeals with corrupt command (in-character, not OOC rulebreaks.)
  id: CentcomOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcomFormalDress
    back: ClothingBackpackSatchelHoldingCentcomOfficerFilled
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    neck: ExecutiveIDCard
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesCCInsideAgent
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSheathFilled
    pocket1: WeaponDisablerAdvanced
    pocket2: WeaponRevolverMateba
  inhand:
  - CentcommMindShieldImplanter
  - DeathRattleImplanterCentcomm
