using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Phones.UI;

[GenerateTypedNameReferences]
public sealed partial class ChangePhoneName : FancyWindow
{
    public event Action<string>? OnTextChanged;
    public event Action<string>? OnCategoryChanged;
    public ChangePhoneName()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        FillCategories();
        MessageEdit.OnTextChanged += _ => OnTextChanged?.Invoke(MessageEdit.Text);
        CategoryOption.OnItemSelected += args =>
        {
            CategoryOption.SelectId(args.Id);
            string selectedText = "hidden";
            switch (args.Id) // if it works, it works
            {
                case 0:
                    selectedText = Loc.GetString("phone-category-command");
                    break;
                case 1:
                    selectedText = Loc.GetString("phone-category-security");
                    break;
                case 2:
                    selectedText = Loc.GetString("phone-category-engineering");
                    break;
                case 3:
                    selectedText = Loc.GetString("phone-category-cargo");
                    break;
                case 4:
                    selectedText = Loc.GetString("phone-category-medical");
                    break;
                case 5:
                    selectedText = Loc.GetString("phone-category-science");
                    break;
                case 6:
                    selectedText = Loc.GetString("phone-category-service");
                    break;
                case 7:
                    selectedText = Loc.GetString("phone-category-uncategorized");
                    break;
                case 8:
                    selectedText = Loc.GetString("phone-category-hidden");
                    break;
            }
            OnCategoryChanged?.Invoke(selectedText);
        };
    }

    private void FillCategories()
    {
        CategoryOption.AddItem(Loc.GetString("phone-category-command"));
        CategoryOption.AddItem(Loc.GetString("phone-category-security"));
        CategoryOption.AddItem(Loc.GetString("phone-category-engineering"));
        CategoryOption.AddItem(Loc.GetString("phone-category-cargo"));
        CategoryOption.AddItem(Loc.GetString("phone-category-medical"));
        CategoryOption.AddItem(Loc.GetString("phone-category-science"));
        CategoryOption.AddItem(Loc.GetString("phone-category-service"));
        CategoryOption.AddItem(Loc.GetString("phone-category-uncategorized"));
        CategoryOption.AddItem(Loc.GetString("phone-category-hidden"));
    }
}
