// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.Forging;

namespace Content.IntegrationTests.Tests._Trauma;

public sealed partial class ForgingTest : GameTest
{
    [SidedDependency(Side.Server)] private IComponentFactory _factory = default!;

    /// <summary>
    /// Checks that all forged item prototypes are sane and that there are no empty categories.
    /// </summary>
    [Test]
    public async Task AllForgedItemsValid()
    {
        var metallicName = _factory.CompName<MetallicComponent>();
        Assert.Multiple(() =>
        {
            var used = new HashSet<ProtoId<ForgingCategoryPrototype>>();
            // sanity check each item prototype
            foreach (var item in SProtoMan.EnumeratePrototypes<ForgedItemPrototype>())
            {
                used.Add(item.Category);

                if (item.Result is {} result)
                {
                    var entity = SProtoMan.Index(result);
                    Assert.That(entity.HasComp(metallicName),
                        $"Result of forging {item.ID}, {result}, must inherit from BaseMetallic!");
                }
                else if (item.Sprite != null)
                {
                    Assert.That(item.Name, Is.Not.EqualTo(string.Empty), $"Forged item {item.ID} must set a name since it is procedurally generated!");
                    if (item.Construction != null)
                    {
                        Assert.That(item.Finished, Is.Not.Null, $"Forged item {item.ID} must have a finished item for its procedural construction graph!");
                    }
                }
                else
                {
                    Assert.Fail($"Result of forging {item.ID} must either be procedurally generated by sprite or a specified result entity!");
                }
            }

            // now check that all categories are used, i.e. not empty
            foreach (var category in SProtoMan.EnumeratePrototypes<ForgingCategoryPrototype>())
            {
                Assert.That(used.Contains(category.ID), $"Forging category {category.ID} is not used by any items!");
            }
        });
    }

    // TODO: test to spawn every material + item combination and simulate working them so theres no errors and check all sprites are valid
}
