- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 2.5h
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  guides: # goobstation
  - Atmospherics
  goobcoins: 20 #Goob content
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe
  - !type:AddComponentSpecial # Goobstation
    components:
    - type: EngineeringStaff
      # <Trauma>
    - type: KnowledgeGrant
      ConstructionSimpleHandmade: 26
      ConstructionAdvancedHandmade: 26
      ConstructionSurvivalWeaponsHandmade: 26
      ConstructionSurvivalWeaponsHandmadeAdvanced: 26
      ConstructionTechnological: 26
      ConstructionMaterials: 26
      ConstructionDoors: 26
      ConstructionAirlocks: 26
      ConstructionToys: 26
      ConstructionBots: 26
      ConstructionSimpleFurniture: 26
      ConstructionFurniture: 26
      ConstructionInfrastructure: 26
      ConstructionElectronics: 26
      ConstructionWalls: 26
      ConstructionAdvancedWalls: 26
      ConstructionScience: 26
      ConstructionWindows: 26
      ConstructionAdvancedWindows: 26
      ConstructionSmokeables: 50
      # </Trauma>


- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: AtmosphericTechnicianChameleonOutfit
  job: AtmosphericTechnician
  equipment:
    head: ClothingHeadHelmetAtmosFire
    mask: ClothingMaskGasAtmos
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterSuitAtmosFire
    gloves: ClothingHandsGlovesColorYellow
