- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 2.5h
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  guides: # goobstation
  - Atmospherics
  goobcoins: 20 #Goob content
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe
  - !type:AddComponentSpecial # Goobstation
    components:
    - type: EngineeringStaff
    # <Trauma>
    - type: KnowledgeGrant
      skills:
        HandmadeKnowledge: 26
        TechnologyKnowledge: 26
        MaterialsKnowledge: 26
        DoorsKnowledge: 26
        AirlocksKnowledge: 26
        FurnitureKnowledge: 26
        InfrastructureKnowledge: 26
        ElectronicsKnowledge: 26
        WallsKnowledge: 26
        WindowsKnowledge: 26
        SmokeablesKnowledge: 50
    # </Trauma>


- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: AtmosphericTechnicianChameleonOutfit
  job: AtmosphericTechnician
  equipment:
    head: ClothingHeadHelmetAtmosFire
    mask: ClothingMaskGasAtmos
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterSuitAtmosFire
    gloves: ClothingHandsGlovesColorYellow
