- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 2.5h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10h
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  #canBeAntag: false
  antagAdvantage: 75 # Goobstation
  guides: # goobstation
  - Engineering
  - Command
  goobcoins: 40 #Goob content
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: EngineeringStaff # Goobstation
      # <Trauma>
      - type: KnowledgeGrant
        skills:
          ConstructionSimpleHandmade: 50
          ConstructionAdvancedHandmade: 50
          ConstructionSurvivalWeaponsHandmade: 50
          ConstructionSurvivalWeaponsHandmadeAdvanced: 50
          ConstructionTechnological: 50
          ConstructionMaterials: 50
          ConstructionDoors: 50
          ConstructionAirlocks: 50
          ConstructionToys: 50
          ConstructionBots: 50
          ConstructionSimpleFurniture: 50
          ConstructionFurniture: 50
          ConstructionInfrastructure: 50
          ConstructionElectronics: 50
          ConstructionWalls: 50
          ConstructionAdvancedWalls: 50
          ConstructionScience: 50
          ConstructionWindows: 50
          ConstructionAdvancedWindows: 50
          ConstructionSmokeables: 50
      # </Trauma>

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetAltEngineering # Goobstation
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckCloakCe
    outerClothing: ClothingOuterWinterCE
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMagAdv
