- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 2.5h
  startingGear: StationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  guides: [ Engineering ] # goobstation
  goobcoins: 20 #Goob content
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics
  special: # Goobstation
  - !type:AddComponentSpecial
    components:
    - type: EngineeringStaff
    # <Trauma>
    - type: KnowledgeGrant
      skills:
        ConstructionSimpleHandmade: 26
        ConstructionAdvancedHandmade: 26
        ConstructionSurvivalWeaponsHandmade: 26
        ConstructionSurvivalWeaponsHandmadeAdvanced: 26
        ConstructionTechnological: 26
        ConstructionMaterials: 26
        ConstructionDoors: 26
        ConstructionAirlocks: 26
        ConstructionToys: 26
        ConstructionBots: 26
        ConstructionSimpleFurniture: 26
        ConstructionFurniture: 26
        ConstructionInfrastructure: 26
        ConstructionElectronics: 26
        ConstructionWalls: 26
        ConstructionAdvancedWalls: 26
        ConstructionScience: 26
        ConstructionWindows: 26
        ConstructionAdvancedWindows: 26
        ConstructionSmokeables: 50
    # </Trauma>
- type: startingGear
  id: StationEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: StationEngineerChameleonOutfit
  job: StationEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
