- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 5h
      inverted: true # stop playing intern if you're good at engineering!
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  guides: # goobstation
  - Construction
  - Power
  - Networking
  goobcoins: 20 #Goob content
  access:
  - Maintenance
  - Engineering
  - External
  # <Trauma>
  special:
  - !type:AddComponentSpecial
    components:
    - type: EngineeringStaff
  - !type:AddKnowledgeSpecial
    knowledge:
      # TODO: make this just 1 or 2 types
      HandmadeKnowledge: 10
      TechnologyKnowledge: 10
      MaterialsKnowledge: 10
      DoorsKnowledge: 10
      AirlocksKnowledge: 10
      FurnitureKnowledge: 10
      InfrastructureKnowledge: 10
      ElectronicsKnowledge: 10
      WallsKnowledge: 10
      WindowsKnowledge: 10
      SmokeablesKnowledge: 50
  # </Trauma>

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: TechnicalAssistantChameleonOutfit
  job: TechnicalAssistant
  equipment:
    head: ClothingHeadHatHardhatOrange
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterVestHazard
    gloves: ClothingHandsGlovesColorYellow
