// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class AttributeTabControl : BoxContainer
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly SpriteSystem _sprite;

    public AttributeTabControl(AttributeInfo conditions)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _system.GetEntitySystem<SpriteSystem>();

        SetTab(conditions);
    }

    public void SetTab(AttributeInfo conditions)
    {
        SkillBox.Text = conditions.Name + ": ";
        ModifierBox.Text = conditions.Inherent.ToString();
    }
}
