// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.Knowledge.Attribute.Attribute;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class AttributeTab : Control
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly KnowledgeSystem _knowledge;
    private readonly SpriteSystem _sprite;

    public AttributeTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _system.GetEntitySystem<KnowledgeSystem>();
        _sprite = _system.GetEntitySystem<SpriteSystem>();
    }

    /// <summary>
    /// Updates the specificied knowledge tab with the player's current martial arts knowledge.
    /// </summary>
    public void UpdateAttributeTab(EntityUid player)
    {
        TabContainer.SetTabTitle(this, Loc.GetString("trauma-attribute-title"));

        AttributeBox.RemoveAllChildren();
        AttributePlaceholder.Visible = true;

        var doohickeys = _knowledge.GrabAllAttributes(player);
        if (doohickeys == null)
            return;

        AttributePlaceholder.Visible = false;
        AttributeBox.SeparationOverride = 10;
        foreach (var (groupId, conditions) in doohickeys)
        {
            var attributeBox = new AttributeTabControl(conditions);
            AttributeBox.AddChild(attributeBox);
        }
    }
}
