// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge;
using Content.Trauma.Common.Knowledge.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class AttributeTabControl : BoxContainer
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly SpriteSystem _sprite;

    public AttributeTabControl(AttributeInfo conditions, EntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _system.GetEntitySystem<SpriteSystem>();

        SetTab(conditions, entMan);
    }

    public void SetTab(AttributeInfo conditions, EntityManager entMan)
    {
        var ent = entMan.GetEntity(conditions.Entity);
        if (!entMan.TryGetComponent<AttributeComponent>(ent, out var attribute))
            return;

        SkillBox.Text = conditions.Name + ": ";
        ModifierBox.Text = attribute.Inherent.ToString();

        var ev = new GetAttributeModifierEvent(new());
        entMan.EventBus.RaiseLocalEvent(entMan.GetEntity(conditions.Entity), ref ev);
        foreach (var (id, number) in ev.Modifiers)
        {
            var box = new AttributeModifierBox(id, number);
            HorizontalContainer.AddChild(box);
        }
    }
}
