using Content.Trauma.Common.Knowledge.Components;
using Content.Trauma.Shared.Knowledge.Attribute.Attribute;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class AttributeControl : BoxContainer
{
    public event Action<int>? OnChangePurchased;
    public int Purchased;

    public AttributeControl(string name)
    {
        RobustXamlLoader.Load(this);

        SkillLabel.Text = name;

        DecreaseButton.OnPressed += _ => OnChangePurchased?.Invoke(-1);
        IncreaseButton.OnPressed += _ => OnChangePurchased?.Invoke(+1);
    }

    public void SetPurchased(int amount, int racialBase = 0)
    {
        Purchased = amount;
        // only show the cost for the added mastery, not net
        var cost = Math.Max(Purchased - racialBase, 0);
        MasteryLabel.Text = $"{AttributeSystem.AdjustAttribute(10.00, Purchased)}, #: {cost}";
        IncreaseButton.Disabled = false;
        DecreaseButton.Disabled = Purchased <= racialBase;
        var color = Purchased - racialBase <= 0 ? Color.Gray : Color.White;
        MasteryLabel.Modulate = color;
        SkillLabel.Modulate = color;
    }
}
