// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.Knowledge.Attribute.Attribute;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class AttributeModifierBox : BoxContainer
{
    public AttributeModifierBox(string modifier, string number)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetText(modifier, number);
    }

    public void SetText(string modifier, string number)
    {
        TextOne.Text = modifier;
        TextTwo.Text = number;
    }
}
