using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class GymWindow : FancyWindow
{
    // Event passed upward to the BoundUserInterface parent wrapper
    public event Action<float>? OnRepPressed;

    private float _rhythmTimer = 0f;
    private float _targetInterval = 1.0f;
    private bool _pingPongDirection = true;

    public GymWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_pingPongDirection)
        {
            _rhythmTimer += args.DeltaSeconds;
            if (_rhythmTimer >= _targetInterval)
            {
                _rhythmTimer = _targetInterval;
                _pingPongDirection = false;
            }
        }
        else
        {
            _rhythmTimer -= args.DeltaSeconds;
            if (_rhythmTimer <= 0f)
            {
                _rhythmTimer = 0f;
                _pingPongDirection = true;
            }
        }


        var percentage = (_rhythmTimer / _targetInterval) * 100f;
        RhythmProgressBar.Value = percentage;

        LayoutContainer.SetMarginLeft(RhythmTrackerImage, percentage * 2.5f);
    }

    /// <summary>
    /// Updates the window's rhythmic pacing based on the item's component data.
    /// </summary>
    public void SetupRhythm(float targetInterval)
    {
        if (targetInterval <= 0)
            return;
        _targetInterval = targetInterval;
    }

    /// <summary>
    /// Handles the input for a single repetition and calculates the accuracy based on the rhythmic pacing.
    /// </summary>
    public float HandleRepInput()
    {
        float maxAllowedError = 0.3f;
        float distanceFromTarget = Math.Abs(_targetInterval - _rhythmTimer);

        float accuracy = Math.Clamp(1.0f - (distanceFromTarget / maxAllowedError), 0.0f, 1.0f);

        OnRepPressed?.Invoke(accuracy);
        return accuracy;
    }
}
