// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Humanoid.Prototypes;
using Content.Trauma.Client.Knowledge;
using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeProfileEditor : BoxContainer
{
    private readonly IPrototypeManager _proto;
    private readonly KnowledgeSystem _knowledge;

    public event Action<KnowledgeProfile>? OnSave;

    private KnowledgeProfilePrototype _parent = default!;
    private KnowledgeProfile _profile = new();
    private bool _modified;

    public KnowledgeProfileEditor(IPrototypeManager proto, KnowledgeSystem knowledge)
    {
        RobustXamlLoader.Load(this);

        _proto = proto;
        _knowledge = knowledge;

        AvailableSkills.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is not EntProtoId id)
                return;

            _profile.Mastery[id] = 0; // cheapest start
            _profile.Removed.Remove(id); // can't be removed if it's added, can it
            _modified = true;
            ReloadSkills();
        };

        SaveButton.OnPressed += _ =>
        {
            OnSave?.Invoke(_profile);
            _modified = false;
            SaveButton.Disabled = true;
        };
    }

    public void SetProfile(ProtoId<SpeciesPrototype> species, KnowledgeProfile profile)
    {
        _profile = profile;
        _parent = _proto.Index(_proto.Index(species).Knowledge);
        ReloadSkills();
    }

    private void ReloadSkills()
    {
        var combined = _profile.AddProfile(_parent.Profile);
        UpdatePoints(combined);

        EnabledSkills.RemoveAllChildren();
        NoSkillsLabel.Visible = combined.Mastery.Count == 0;
        foreach (var (id, mastery) in combined.Mastery)
        {
            var name = _proto.Index(id).Name;
            var comp = _knowledge.AllKnowledges[id];
            if (comp.Costs is not {} costs)
            {
                Log.Error($"Invalid skill {id} in profile!");
                continue;
            }

            // a lot of the logic here is evil because the UI displays combined parent + diff, but internally its only modifying the diff
            var control = new SkillControl(name, costs);
            control.SetMastery(_knowledge.GetMasteryString(mastery), mastery);
            control.OnChangeMastery += diff =>
            {
                var sum = control.Mastery + diff;
                if (sum > 5)
                    return;

                if (sum < 0)
                {
                    control.Orphan();
                    _profile.Mastery.Remove(id);
                    if (_parent.Profile.Mastery.ContainsKey(id))
                        _profile.Removed.Add(id);
                    // removed the skill so now it can be added again
                    AddAvailableSkill(id, costs[0]);
                }
                else
                {
                    control.SetMastery(_knowledge.GetMasteryString(sum), sum);
                    _profile.Mastery[id] = _profile.Mastery.GetValueOrDefault(id) + diff;
                }
                _modified = true;
                UpdatePoints();
            };
            EnabledSkills.AddChild(control);
        }

        AvailableSkills.Clear();
        foreach (var (id, comp) in _knowledge.AllKnowledges)
        {
            // don't list ones that are already added
            if (combined.Mastery.ContainsKey(id) || comp.Costs is not {} costs)
                continue;

            AddAvailableSkill(id, costs[0]);
        }
    }

    private void AddAvailableSkill(EntProtoId id, int cost)
    {
        var name = _proto.Index(id).Name;
        var text = Loc.GetString("knowledge-editor-item", ("name", name), ("cost", cost));
        AvailableSkills.AddItem(text, metadata: id);
    }

    private void UpdatePoints()
    {
        var combined = _profile.AddProfile(_parent.Profile);
        UpdatePoints(combined);
    }

    private void UpdatePoints(KnowledgeProfile combined)
    {
        var points = _knowledge.PointLimits[_parent];
        var cost = _knowledge.ProfileCost(combined);
        points -= cost;
        PointsLabel.Text = Loc.GetString("knowledge-editor-points", ("points", points));
        if (points >= 0)
        {
            SaveButton.Disabled = !_modified;
            return;
        }

        // can't save with a deficit
        SaveButton.Disabled = true;
        // TODO: show deficit text somewhere
    }
}
