// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Humanoid.Prototypes;
using Content.Trauma.Client.Knowledge;
using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeProfileEditor : BoxContainer
{
    private readonly IPrototypeManager _proto;
    private readonly KnowledgeSystem _knowledge;

    public event Action<KnowledgeProfile>? OnSave;

    private KnowledgeProfilePrototype _parent = default!;
    private KnowledgeProfile _profile = default!;

    public KnowledgeProfileEditor(IPrototypeManager proto, KnowledgeSystem knowledge)
    {
        RobustXamlLoader.Load(this);

        _proto = proto;
        _knowledge = knowledge;

        AvailableSkills.OnItemSelected += args =>
        {
            var id = (EntProtoId) args.ItemList[args.ItemIndex].Metadata;
            _profile.Mastery[id] = 0;
            UpdatePoints();
            // TODO
        };

        SaveButton.OnPressed += _ =>
        {
            OnSave?.Invoke(_profile);
            SaveButton.Disabled = true;
        };
    }

    public void SetProfile(ProtoId<SpeciesPrototype> species, KnowledgeProfile profile)
    {
        _profile = profile;
        _parent = _proto.Index(_proto.Index(species).Knowledge);
        var combined = profile.AddProfile(_parent.Profile);
        UpdatePoints(combined);

        EnabledSkills.RemoveAllChildren();
        foreach (var (id, mastery) in combined.Mastery)
        {
            var name = _proto.Index(id).Name;
            var comp = _knowledge.AllKnowledges[id];
            var control = new SkillControl(name, comp);
            control.SetMastery(_knowledge.GetMasteryString(mastery), mastery);
            control.OnChangeMastery += add =>
            {
                var sum = mastery + add;
                if (sum > 5)
                    return;

                if (sum < 0)
                {
                    control.Orphan();
                    _profile.Mastery.Remove(id);
                }
                else
                {
                    control.SetMastery(_knowledge.GetMasteryString(sum), sum);
                    _profile.Mastery[id] = sum;
                }
                UpdatePoints();
            };
            EnabledSkills.AddChild(control);
        }

        AvailableSkills.Clear();
        // TODO
        foreach (var (id, comp) in _knowledge.AllKnowledges)
        {
            // exclude ones that are already added
            if (combined.Mastery.ContainsKey(id))
                continue;

            var name = _proto.Index(id).Name;
            var cost = comp.Costs[0]; // cost to just enable it
            var text = Loc.GetString("knowledge-editor-item", ("name", name), ("cost", cost));
            AvailableSkills.AddItem(text, metadata: id);
        }
    }

    private void UpdatePoints()
    {
        var combined = _profile.AddProfile(_parent.Profile);
        UpdatePoints(combined);
    }

    private void UpdatePoints(KnowledgeProfile combined)
    {
        var points = _parent.Points;
        var cost = _knowledge.ProfileCost(combined);
        points -= cost;
        PointsLabel.Text = Loc.GetString("knowledge-editor-points", ("points", points));
        if (points >= 0)
            return;

        // can't save with a deficit
        SaveButton.Disabled = true;
        // TODO: show deficit text somewhere
    }
}
