// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillControl : BoxContainer
{
    public event Action<int>? OnChangeRolls;
    private readonly int _costs;
    public int Rolls;

    public SkillControl(string name, int costs)
    {
        RobustXamlLoader.Load(this);

        _costs = costs;

        SkillLabel.Text = name;

        DecreaseButton.OnPressed += _ => OnChangeRolls?.Invoke(-1);
        IncreaseButton.OnPressed += _ => OnChangeRolls?.Invoke(+1);
    }

    public void SetRolls(int rolls, int racialBase = 0)
    {
        Rolls = rolls;
        // only show the cost for the added mastery, not net
        var amount = Math.Max(Rolls - racialBase, 0);
        var cost = _costs * amount;
        MasteryLabel.Text = $"Cost: {cost}, Rolls: {Rolls}";
        IncreaseButton.Disabled = false;
        DecreaseButton.Disabled = Rolls <= racialBase;
        var color = Rolls - racialBase <= 0 ? Color.Gray : Color.White;
        MasteryLabel.Modulate = color;
        SkillLabel.Modulate = color;
    }
}
