// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillTabControl : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _system = default!;
    private readonly SpriteSystem _sprite;

    public SkillTabControl(SkillInfo conditions)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _system.GetEntitySystem<SpriteSystem>();

        SetTab(conditions);
    }

    public void SetTab(SkillInfo conditions)
    {
        if (conditions.Sprite != null)
            TextRect.Texture = _sprite.Frame0(conditions.Sprite);

        SkillText.Text = conditions.Name;
        SkillText.Modulate = conditions.Color;

        MasteryText.Text = conditions.Description;
        MasteryText.Modulate = conditions.Color;

        ExpBar.MaxValue = conditions.ExpCost;
        ExpBar.Value = conditions.CurrentExp;
    }
}
