// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Content.Trauma.Common.Knowledge;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillTab : Control
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly KnowledgeSystem _knowledge;
    private readonly SpriteSystem _sprite;

    public SkillTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _system.GetEntitySystem<KnowledgeSystem>();
        _sprite = _system.GetEntitySystem<SpriteSystem>();
    }

    /// <summary>
    /// Updates the specificied knowledge tab with the player's current martial arts knowledge.
    /// </summary>
    public void UpdateSkillTab(EntityUid player)
    {
        TabContainer.SetTabTitle(this, Loc.GetString("trauma-skill-title"));

        // Remove children from skill tabs instead of removing everything so that there is premeance between refresh.
        var children = SkillBox.Children;
        foreach (Control? child in children)
        {
            if (child is Collapsible collapse)
                collapse.Body?.GetChild(0)?.RemoveAllChildren();
        }

        var doohickeys = _knowledge.GrabAllSkills(player);
        if (doohickeys == null || doohickeys.Count == 0)
        {
            SkillBox.RemoveAllChildren();
            SkillPlaceholder.Visible = true;
            return;
        }

        SkillPlaceholder.Visible = false;
        SkillBox.SeparationOverride = 10;
        foreach (var (groupId, conditions) in doohickeys)
        {
            SkillTabControl? boxContainer = new SkillTabControl(conditions);

            //Find category.
            Collapsible? groupContainer = null;
            foreach (Control? child in SkillBox.Children)
            {
                if (child is not Collapsible childNotNull || childNotNull.Name != groupId.Id)
                    continue;

                groupContainer = childNotNull;
            }

            // Create category if category not found.
            if (groupContainer is not { })
            {
                var body = new CollapsibleBody();
                var innerStack = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Name = "InnerStack",
                    SeparationOverride = 10
                };
                body.AddChild(innerStack);
                groupContainer = new Collapsible(groupId.Id, body);
                groupContainer.Name = groupId.Id;
                SkillBox.AddChild(groupContainer);
            }

            // Add skill to category.
            groupContainer.Body?.GetChild(0)?.AddChild(boxContainer);
        }

        // Cleanup empty tabs.
        var childrenCache = SkillBox.Children.ToArray();
        foreach (Control? child in childrenCache)
        {
            if (child is Collapsible collapse && collapse.Body?.GetChild(0)?.ChildCount == 0)
                SkillBox.RemoveChild(child);
        }
    }
}
