// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillControl : BoxContainer
{
    public event Action<int>? OnChangeMastery;

    private readonly int[] _costs;
    public int Mastery;

    public SkillControl(string name, int[] costs)
    {
        RobustXamlLoader.Load(this);

        _costs = costs;

        SkillLabel.Text = name;

        DecreaseButton.OnPressed += _ => OnChangeMastery?.Invoke(-1);
        IncreaseButton.OnPressed += _ => OnChangeMastery?.Invoke(+1);
    }

    public void SetMastery(string name, int mastery)
    {
        Mastery = mastery;
        var cost = _costs[mastery];
        MasteryLabel.Text = Loc.GetString("knowledge-editor-mastery", ("mastery", name), ("cost", cost));
        // decrease button is also used for removing, only increase can be disabled
        IncreaseButton.Disabled = mastery >= 5;
    }
}
