- type: entity
  parent: OrganHuman
  id: OrganWorkingJoeExternal
  abstract: true
  components:
  - type: Sprite
    sprite: _AU14/Mobs/WorkingJoe/parts.rsi
  - type: VisualOrgan
    data:
      sprite: _AU14/Mobs/WorkingJoe/parts.rsi
  - type: VisualOrganMarkings
    markingData:
      group: Human

- type: entity
  parent: [ OrganBaseTorsoSexed, OrganBaseTorso, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeTorso

- type: entity
  parent: [ OrganBaseHeadSexed, OrganBaseHead, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeHead

- type: entity
  parent: [ OrganBaseArmLeft, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeArmLeft

- type: entity
  parent: [ OrganBaseArmRight, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeArmRight

- type: entity
  parent: [ OrganBaseHandLeft, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeHandLeft

- type: entity
  parent: [ OrganBaseHandRight, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeHandRight

- type: entity
  parent: [ OrganBaseLegLeft, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeLegLeft

- type: entity
  parent: [ OrganBaseLegRight, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeLegRight

- type: entity
  parent: [ OrganBaseFootLeft, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeFootLeft

- type: entity
  parent: [ OrganBaseFootRight, OrganWorkingJoeExternal ]
  id: OrganWorkingJoeFootRight

- type: entity
  parent: BaseSpeciesAppearance
  id: AppearanceWorkingJoe
  categories: [ HideSpawnMenu ]
  name: working joe appearance
  components:
  - type: InitialBody
    organs:
      Torso: OrganWorkingJoeTorso
      Head: OrganWorkingJoeHead
      ArmLeft: OrganWorkingJoeArmLeft
      ArmRight: OrganWorkingJoeArmRight
      HandRight: OrganWorkingJoeHandRight
      HandLeft: OrganWorkingJoeHandLeft
      LegLeft: OrganWorkingJoeLegLeft
      LegRight: OrganWorkingJoeLegRight
      FootLeft: OrganWorkingJoeFootLeft
      FootRight: OrganWorkingJoeFootRight
      Brain: OrganHumanBrain
      Eyes: OrganHumanEyes
      Tongue: OrganHumanTongue
      Appendix: OrganHumanAppendix
      Ears: OrganHumanEars
      Lungs: OrganHumanLungs
      Heart: OrganHumanHeart
      Stomach: OrganHumanStomach
      Liver: OrganHumanLiver
      Kidneys: OrganHumanKidneys
  - type: HumanoidProfile
    species: WorkingJoe

- type: entity
  parent:
  - AppearanceWorkingJoe
  - BaseSpeciesMobOrganic
  id: AU14MobWorkingJoe
  name: Working Joe
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    reregister: false
    name: au14-job-name-workingjoe
    description: au14-job-description-workingjoe
    raffle:
      settings: short
  - type: Icon
    sprite: _AU14/Mobs/WorkingJoe/parts.rsi
    state: full
  - type: WorkingJoeVoice
  - type: UserInterface
    interfaces:
      enum.WorkingJoeVoiceUiKey.Key:
        type: WorkingJoeVoiceBui
  - type: Vocal
    sounds:
      Male: AU14WorkingJoeSounds
      Female: AU14WorkingJoeSounds
      Unsexed: AU14WorkingJoeSounds
  - type: TypingIndicator
    proto: joe
  - type: IntrinsicRadioReceiver
  - type: IntrinsicRadioTransmitter
    channels:
    - AI
    - Common
  - type: ActiveRadio
    channels:
    - AI
    - Common
  - type: MeleeWeapon
    soundHit:
      path: /Audio/Effects/punch1.ogg
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 15
