# SPDX-License-Identifier: AGPL-3.0-or-later

- type: randomHumanoidSettings
  id: VisitorCaptain
  components:
  - type: GhostRole
    job: Captain

- type: randomHumanoidSettings
  id: VisitorCE
  components:
  - type: GhostRole
    job: ChiefEngineer

- type: randomHumanoidSettings
  id: VisitorCMO
  components:
  - type: SurgerySpeedModifier # TODO: move ts to skillchip
    speedModifier: 2
  - type: CPRTraining
    reviveChance: 0.9 # excellent training and experience
    inhaleChance: 1 # great kisser too
  - type: GhostRole
    job: ChiefMedicalOfficer

- type: randomHumanoidSettings
  id: VisitorHOP
  components:
  - type: GhostRole
    job: HeadOfPersonnel

- type: randomHumanoidSettings
  id: VisitorHOS
  components:
  - type: GhostRole
    job: HeadOfSecurity

- type: randomHumanoidSettings
  id: VisitorResearchDirector
  components:
  - type: GhostRole
    job: ResearchDirector

- type: randomHumanoidSettings
  id: VisitorQM
  components:
  - type: GhostRole
    job: Quartermaster

# Security

- type: randomHumanoidSettings
  id: VisitorSecurityCadet
  components:
  - type: GhostRole
    job: SecurityCadet

- type: randomHumanoidSettings
  id: VisitorSecurityOfficer
  components:
  - type: GhostRole
    job: SecurityOfficer

- type: randomHumanoidSettings
  id: VisitorDetective
  components:
  - type: GhostRole
    job: Detective

- type: randomHumanoidSettings
  id: VisitorWarden
  components:
  - type: GhostRole
    job: Warden

# Cargo

- type: randomHumanoidSettings
  id: VisitorCargoTechnician
  components:
  - type: GhostRole
    job: CargoTechnician

- type: randomHumanoidSettings
  id: VisitorSalvageSpecialist
  components:
  - type: GhostRole
    job: SalvageSpecialist

# Engineering

- type: randomHumanoidSettings
  id: VisitorAtmosTech
  components:
  - type: GhostRole
    job: AtmosphericTechnician

- type: randomHumanoidSettings
  id: VisitorTechnicalAssistant
  components:
  - type: GhostRole
    job: TechnicalAssistant

- type: randomHumanoidSettings
  id: VisitorEngineer
  components:
  - type: GhostRole
    job: StationEngineer

# Medical

- type: randomHumanoidSettings
  id: VisitorMedicalIntern
  components:
  - type: GhostRole
    job: MedicalIntern

- type: randomHumanoidSettings
  id: VisitorMedicalDoctor
  components:
  - type: GhostRole
    job: MedicalDoctor

- type: randomHumanoidSettings
  id: VisitorParamedic
  components:
  - type: GhostRole
    job: Paramedic

- type: randomHumanoidSettings
  id: VisitorVirologist
  components:
  - type: GhostRole
    job: Virologist

- type: randomHumanoidSettings
  id: VisitorGeneticist
  components:
  - type: GhostRole
    job: Geneticist

- type: randomHumanoidSettings
  id: VisitorPsychologist
  components:
  - type: GhostRole
    job: Psychologist

- type: randomHumanoidSettings
  id: VisitorChemist
  components:
  - type: GhostRole
    job: Chemist

# Science

- type: randomHumanoidSettings
  id: VisitorResearchAssistant
  components:
  - type: GhostRole
    job: ResearchAssistant

- type: randomHumanoidSettings
  id: VisitorScientist
  components:
  - type: GhostRole
    job: Scientist

# Service

- type: randomHumanoidSettings
  id: VisitorBartender
  components:
  - type: GhostRole
    job: Bartender

- type: randomHumanoidSettings
  id: VisitorBotanist
  components:
  - type: GhostRole
    job: Botanist

- type: randomHumanoidSettings
  id: VisitorChef
  components:
  - type: GhostRole
    job: Chef

- type: randomHumanoidSettings
  id: VisitorServiceWorker
  components:
  - type: GhostRole
    job: ServiceWorker

# Civilian

- type: randomHumanoidSettings
  id: VisitorChaplain
  components:
  - type: CurseImmune
  - type: GhostRole
    job: Chaplain

- type: randomHumanoidSettings
  id: VisitorClown
  components:
  - type: GhostRole
    job: Clown

- type: randomHumanoidSettings
  id: VisitorJanitor
  components:
  - type: GhostRole
    job: Janitor

- type: randomHumanoidSettings
  id: VisitorLawyer
  components:
  - type: GhostRole
    job: Lawyer

- type: randomHumanoidSettings
  parent: VisitorLawyer
  id: VisitorLawyerCentcom

- type: randomHumanoidSettings
  id: VisitorLibrarian
  components:
  - type: GhostRole
    job: Librarian

- type: randomHumanoidSettings
  id: VisitorMusician
  components:
  - type: GhostRole
    job: Musician

- type: randomHumanoidSettings
  parent: VisitorMusician
  id: VisitorMusicianFancy

- type: randomHumanoidSettings
  parent: VisitorMusician
  id: VisitorMusicianRelaxed

- type: randomHumanoidSettings
  id: VisitorMime
  components:
  - type: GhostRole
    job: Mime

- type: randomHumanoidSettings
  id: VisitorReporter
  components:
  - type: GhostRole
    job: Reporter

## Challenge

- type: randomHumanoidSettings
  id: ChallengeVictimCaptain
  components:
  - type: GhostRole
    job: Captain

- type: randomHumanoidSettings
  id: ChallengeVictimChiefEngineer
  components:
  - type: GhostRole
    job: ChiefEngineer

- type: randomHumanoidSettings
  id: ChallengeVictimCMO
  components:
  - type: GhostRole
    job: ChiefMedicalOfficer

- type: randomHumanoidSettings
  id: ChallengeVictimHeadOfPersonnel
  components:
  - type: GhostRole
    job: HeadOfPersonnel

- type: randomHumanoidSettings
  id: ChallengeVictimHeadOfSecurity
  components:
  - type: GhostRole
    job: HeadOfSecurity

- type: randomHumanoidSettings
  id: ChallengeVictimResearchDirector
  components:
  - type: GhostRole
    job: ResearchDirector

- type: randomHumanoidSettings
  id: ChallengeVictimQuartermaster
  components:
  - type: GhostRole
    job: Quartermaster

- type: randomHumanoidSettings
  id: ChallengeCargoTechnician
  components:
  - type: GhostRole
    job: CargoTechnician
    rules: ghost-role-information-lost-challenge-cargo-technican-rules # it had a typo lol

- type: randomHumanoidSettings
  id: SyndieSoldierTeamLeader
  components:
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipSyndieSoldierTeamLeader

- type: randomHumanoidSettings
  id: SyndieSoldier
  components:
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipSyndieSoldier

- type: randomHumanoidSettings
  id: SyndieVisitor
  components:
  - type: GhostRole
    rules: ghost-role-information-nonantagonist-rules
    mindRoles: !Clear []
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipSyndieVisitor

- type: randomHumanoidSettings
  id: PirateScooner
  components:
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipPirateScooner

- type: randomHumanoidSettings
  id: PirateCaptainScooner
  components:
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipPirateCaptainScooner

- type: randomHumanoidSettings
  id: VisitorBlackmarketeer
  parent: EventHumanoid
  components:
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipBlackmarketeer

- type: randomHumanoidSettings
  id: Cossack
  components:
  - type: TriggerOnSpawn
  - type: EntityEffectOnTrigger
    effects:
    - !type:InstallOrganChip
      chip: SkillChipCossack
