// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Circuits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Trauma.Client.Circuits.UI;

[GenerateTypedNameReferences]
public sealed partial class CircuitEditorWindow : FancyWindow
{
    [Dependency] private IResourceCache _cache = default!;

    public event Action? OnClear;
    public event Action? OnImport;
    public event Action? OnExport;
    public event Action<CircuitGate>? OnAddGate;
    public event Action<int, Vector2>? OnMoveGate;
    public event Action<int>? OnRemoveGate;
    public event Action<int, int, int>? OnLinkGate;
    public event Action<int, int>? OnUnlinkGate;

    private bool _hasCircuit;
    private CircuitGateControl? _selected;

    private static readonly ResPath TexturePath = new("/Textures/_Trauma/Interface/circuits_grid.png");

    public CircuitEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // center scroll after ui is ready
        UserInterfaceManager.DeferAction(() =>
        {
            GatesScroll.SetScrollValue(new Vector2(280f, 280f));
        });
        GatesPanel.PanelOverride = new StyleBoxTexture()
        {
            Texture = _cache.GetResource<TextureResource>(TexturePath).Texture,
            Mode = StyleBoxTexture.StretchMode.Tile
        };

        ClearButton.OnPressed += _ =>
        {
            if (_hasCircuit)
                OnClear?.Invoke();
        };
        ImportButton.OnPressed += _ =>
        {
            if (_hasCircuit)
                OnImport?.Invoke();
        };
        ExportButton.OnPressed += _ =>
        {
            if (_hasCircuit)
                OnExport?.Invoke();
        };
        DeleteButton.OnPressed += _ =>
        {
            if (_selected is {} selected)
            {
                OnRemoveGate?.Invoke(selected.Index);
                _selected = null;
            }
        };
        // TODO: selecting gates
        // TODO: click gate from list on the left then drop it in the area to add gate
        // TODO: drag title bar to move gates
        // TODO: mouse dragging for linking
    }

    public void UpdateState(CircuitEditorState state)
    {
        _hasCircuit = state.Data != null;
        var isEmpty = state.Data?.Gates?.Count is not { } count || count == 0;

        ClearButton.Disabled = isEmpty;
        ImportButton.Disabled = !_hasCircuit;
        ExportButton.Disabled = isEmpty;

        var selected = _selected?.Index;
        _selected = null;
        GatesContainer.RemoveAllChildren();
        if (state.Data is { } data)
        {
            GateCountLabel.Text = $"{data.Gates.Count} gates total";
            for (var i = 0; i < data.Gates.Count; i++)
            {
                var gate = data.Gates[i];
                var control = new CircuitGateControl(gate, i);
                if (i == selected)
                    _selected = control;
                GatesContainer.AddChild(control);
            }
        }
        else
        {
            GateCountLabel.Text = "No circuit inserted!";
        }
    }
}
