// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Circuits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Circuits.UI;

[GenerateTypedNameReferences]
public sealed partial class CircuitEditorWindow : FancyWindow
{
    public CircuitEditorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CircuitEditorState state)
    {
        // TODO
    }
}
