// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.Circuits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Circuits.UI;

[GenerateTypedNameReferences]
public sealed partial class CircuitGateControl : BoxContainer
{
    public readonly CircuitGate Gate;
    public readonly int Index;

    public CircuitGateControl(CircuitGate gate, int index)
    {
        RobustXamlLoader.Load(this);

        Gate = gate;
        Index = index;

        NameLabel.Text = gate.Name();
    }
}
