// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ListEntitySelector;

[GenerateTypedNameReferences]
public sealed partial class ListEntitySelectorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public Action<EntityUid>? OnPressEntity;

    public ListEntitySelectorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Populates the window with a hashset of entities.
    /// Each entity represents a button, which when clicked raises a <see cref="OnPressEntity"/>,
    /// and informs the BUI owner via a message.
    /// </summary>
    public void PopulateWindow(HashSet<NetEntity> entities, string windowTitle)
    {
        Title = windowTitle;
        EntityContainer.DisposeAllChildren();

        foreach (var ent in entities)
        {
            var entity = _entMan.GetEntity(ent);
            var button = new Button()
            {
                Text = Identity.Name(entity, _entMan),
            };

            EntityContainer.AddChild(button);
            button.OnPressed += _ => OnPressEntity?.Invoke(entity);
        }
    }
}
