- type: entity
  id: BaseAttribute
  abstract: true
  components:
  - type: Attribute
    inherent: 1.01

- type: entity
  id: StrengthAttribute
  name: Strength
  parent: BaseAttribute
  components:
  - type: DamageAttribute
    minX: 1.01
    maxX: 20.51
    minY: -14
    maxY: 14
  - type: LiftAttribute
    minX: 1.01
    maxX: 20.51
    minY: 32
    maxY: 675
  - type: CarryAttribute
    minX: 1.01
    maxX: 20.51
    minY: 15
    maxY: 384
  - type: DragAttribute
    minX: 1.01
    maxX: 20.51
    minY: 80
    maxY: 1688
  - type: StrengthFeat
    minX: 1.01
    maxX: 20.51
    minY: -14
    maxY: 18
  - type: Attribute
    order: 0

- type: entity
  id: IntelligenceAttribute
  name: Intelligence
  parent: BaseAttribute
  components:
  - type: AttackAttribute
    minX: 1.01
    maxX: 20.01
    minY: -5
    maxY: 3
  - type: Attribute
    order: 1

- type: entity
  id: WisdomAttribute
  name: Wisdom
  parent: BaseAttribute
  components:
  - type: DefenseAttribute
    minX: 1.01
    maxX: 20.51
    minY: -4
    maxY: 3
  - type: MentalAttribute
    minX: 1.01
    maxX: 20.01
    minY: -5
    maxY: 4
  - type: Attribute
    order: 2

- type: entity
  id: DexterityAttribute
  name: Dexterity
  parent: BaseAttribute
  components:
  - type: AttackAttribute
    minX: 3.01
    maxX: 20.51
    minY: -4
    maxY: 5
  - type: DefenseAttribute
    minX: 3.01
    maxX: 20.51
    minY: -5
    maxY: 7
  - type: AgilityFeat
    minX: 3.01
    maxX: 20.51
    minY: -10
    maxY: 18
  - type: DodgeAttribute
    minX: 3.01
    maxX: 20.51
    minY: -3
    maxY: 3
  - type: Attribute
    order: 3

- type: entity
  id: ConstitutionAttribute
  name: Constitution
  parent: BaseAttribute
  components:
  - type: PhysicalAttribute
    minX: 1.01
    maxX: 22.01
    minY: -5
    maxY: 6
  - type: Attribute
    order: 4

- type: entity
  id: LooksAttribute
  name: Looks
  parent: BaseAttribute
  components:
  - type: Attribute
    order: 5

- type: entity
  id: CharismaAttribute
  name: Charisma
  parent: BaseAttribute
  components:
  - type: MoraleAttribute
    minX: 1.01
    maxX: 22.01
    minY: -5
    maxY: 6
  - type: Attribute
    order: 6
