// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.Tabs;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeTab : Control
{
    [Dependency] private readonly IEntitySystemManager _system = default!;
    private readonly KnowledgeSystem _knowledge;
    private readonly SpriteSystem _sprite;

    public KnowledgeTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _system.GetEntitySystem<KnowledgeSystem>();
        _sprite = _system.GetEntitySystem<SpriteSystem>();
    }

    /// <summary>
    /// Updates the specificied knowledge tab with the player's current martial arts knowledge.
    /// </summary>
    /// <param name="player"></param>
    /// <param name="knowledgeTab"></param>
    public void UpdateKnowledgeTab(EntityUid? player, KnowledgeTab knowledgeTab)
    {
        if (player is not { } truePlayer)
            return;

        TabContainer.SetTabTitle(knowledgeTab, Loc.GetString("trauma-knowledge-title"));

        knowledgeTab.KnowledgeBox.RemoveAllChildren();
        knowledgeTab.KnowledgePlaceholder.Visible = true;

        var doohickeys = _knowledge.GrabAllKnowledge(truePlayer);
        if (doohickeys == null)
            return;

        knowledgeTab.KnowledgePlaceholder.Visible = false;
        knowledgeTab.KnowledgeBox.SeparationOverride = 10;
        foreach (var (groupId, conditions) in doohickeys)
        {
            var boxContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var textRect = new TextureRect
            {
                Margin = new Thickness(0, 8, 0, 0),
            };
            if (conditions.Sprite != null)
                textRect.Texture = _sprite.Frame0(conditions.Sprite);

            var box = new BoxContainer
            {
                MinSize = new System.Numerics.Vector2(10, 0),
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            var skillText = new RichTextLabel
            {
                Text = conditions.Name,
                Modulate = conditions.Color,
                SetWidth = 325,
                HorizontalAlignment = HAlignment.Left,
            };

            var masteryText = new RichTextLabel
            {
                Text = conditions.Description,
                Modulate = conditions.Color,
                SetWidth = 325,
                HorizontalAlignment = HAlignment.Left,
                StyleClasses = { "LabelSubText" }
            };

            box.AddChild(skillText);
            box.AddChild(masteryText);
            boxContainer.AddChild(textRect);
            boxContainer.AddChild(box);
            knowledgeTab.KnowledgeBox.AddChild(boxContainer);
        }
    }
}
