// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Shitcode.UserActions.Tabs;
using Content.Goobstation.UIKit.UserActions.Controls;
using Content.Trauma.Common.MartialArts;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;

namespace Content.Trauma.Client.Knowledge.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MartialArtsTabControl : BaseTabControl
{
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IEntitySystemManager _system = default!;
    private readonly KnowledgeSystem _knowledge;
    private readonly SpriteSystem _sprite;

    public MartialArtsTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _system.GetEntitySystem<KnowledgeSystem>();
        _sprite = _system.GetEntitySystem<SpriteSystem>();
    }

    public override bool UpdateState()
    {
        MartialArtsList.RemoveAllChildren();

        if (_player.LocalEntity is not { } player || _knowledge.TryGetKnowledgeEntity(player) is not { } knowledgeEntity)
            return false;

        var martialArts = _knowledge.TryGetKnowledgeWithComp<MartialArtsKnowledgeComponent>(knowledgeEntity);

        var button = CreateMartialArtsButton(knowledgeEntity, null);
        MartialArtsList.AddChild(button);

        if (martialArts is { })
        {
            foreach (var martialArt in martialArts)
            {
                button = CreateMartialArtsButton(knowledgeEntity, martialArt);
                MartialArtsList.AddChild(button);
            }
        }
        return true;
    }


    private IconButton CreateMartialArtsButton(EntityUid knowledgeEntity, Entity<MartialArtsKnowledgeComponent>? martialArt)
    {
        string locString = _knowledge.GetEntProtoId(martialArt) ?? "no-martial-art";

        var button = new IconButton(Loc.GetString(locString));
        if (martialArt is { } martialArtTrue)
            button.Icon.Texture = _sprite.Frame0(martialArtTrue.Comp.Icon);
        button.OnPressed += _ => OnChangeMartialArts(knowledgeEntity, martialArt);

        return button;
    }

    private void OnChangeMartialArts(EntityUid knowledgeEntity, Entity<MartialArtsKnowledgeComponent>? martialArt)
    {
        _knowledge.ChangeMartialArts(knowledgeEntity, martialArt);
    }
}
