// SPDX-License-Identifier: AGPL-3.0-or-later
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Log;
using Robust.Shared.Prototypes;

namespace Content.Client._Shitcode.Wizard.MagicMirror;

// almost all of this file is imports because an idiot didnt use ioc :)
[GenerateTypedNameReferences]
public sealed partial class WizardMirrorWindow : FancyWindow
{
    [Dependency] private readonly IClientPreferencesManager _prefs = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IFileDialogManager _dialog = default!;
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IResourceManager _res = default!;
    [Dependency] private readonly JobRequirementsManager _jobReq = default!;
    [Dependency] private readonly MarkingManager _marking = default!;

    public readonly HumanoidProfileEditor Editor;

    public HashSet<ProtoId<SpeciesPrototype>>? AllowedSpecies;

    public const int TraitsTab = 3;
    public const int JobsTab = 1;

    public WizardMirrorWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        // use ioc you fucking monkey
        Editor = new HumanoidProfileEditor(_prefs, _cfg, _entMan, _dialog, _log, _player, _proto, _res, _jobReq, _marking);
        // hide Traits (3), Antags (2), Jobs (1) tabs
        for (int i = TraitsTab; i >= JobsTab; i--)
        {
            TabContainer.SetTabVisible(Editor.TabContainer.GetChild(i), false);
        }
        AddChild(Editor);
    }
}
