// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.GameTicking.Managers;
using Content.Shared.Chat;
using Content.Shared.Chat.Prototypes;
using Content.Shared.Speech;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StatusTabControl : BaseTabControl
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private ClientGameTicker? _gameTicker;

    public StatusTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs e)
    {
        if (_gameTicker is { })
        {
            var roundTime = _timing.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }

        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");
    }

    public override bool UpdateState()
    {
        if (_entMan is not { })
            return false;

        if (_gameTicker is not { })
        {
            if (!_entMan.TrySystem<ClientGameTicker>(out var ticker))
            {
                return false;
            }
            _gameTicker = ticker;
            _gameTicker.InGameInfoBlobUpdated += UpdateInfoBlob;
        }
        UpdateInfoBlob();
        return true;
    }

    private void UpdateInfoBlob()
    {
        if (_gameTicker?.InGameInfoBlob is { } info)
            ServerInfo.SetInfoBlob(info);
    }
}
