// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.GameTicking.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controllers;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StatusTabControl : BaseTabControl, IOnSystemChanged<ClientGameTicker>
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private ClientGameTicker? _gameTicker;

    public StatusTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void OnSystemLoaded(ClientGameTicker system)
    {
        _gameTicker = system;
        _gameTicker.InGameInfoBlobUpdated += UpdateInfoBlob;
        UpdateInfoBlob();
    }

    public void OnSystemUnloaded(ClientGameTicker system)
    {
        if (_gameTicker is { })
            _gameTicker.InGameInfoBlobUpdated -= UpdateInfoBlob;
    }


    protected override void FrameUpdate(FrameEventArgs e)
    {
        if (_gameTicker is { })
        {
            var roundTime = _timing.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }

        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");
    }

    public override bool UpdateState()
    {
        UpdateInfoBlob();
        return true;
    }

    private void UpdateInfoBlob()
    {
        if (_gameTicker?.InGameInfoBlob is { } info)
            ServerInfo.SetInfoBlob(info);
    }
}
