# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  abstract: true
  id: BaseStationCargo
  components:
  - type: StationBankAccount
    primaryCut: 0.9
  - type: StationCargoBountyDatabase
    maxBounties: 8
  - type: StationXenobiologyBountyDatabase
