- type: entity
  id: BaseStationCargo
  abstract: true
  components:
  - type: StationBankAccount
    primaryCut: 0.9
  - type: StationCargoBountyDatabase
    maxBounties: 8
  - type: StationXenobiologyBountyDatabase