# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: BaseBullet
  components:
  - type: Physics
    bodyStatus: InAir
  - type: Projectile
    damage:
      types: !Clear
        Ballistic: 14

- type: entity
  id: BaseBulletIncendiary
  components:
  - type: Projectile
    damage:
      types: !Clear
        Ballistic: 10
        Heat: 4
  - type: IgniteOnCollide
    fireStacks: 0.5

- type: entity
  id: BaseBulletAP
  components:
  - type: Projectile
    damage:
      types: !Clear
        Ballistic: 11
    ignoreResistances: false
    increaseOnly: true # apply modifiers, but ignore decreases
