# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagSpecifier
  id: TheXenomorph
  prefRoles: [ Xenomorph ]
  spawnerPrototype: SpawnPointGhostAlien
  allowNonHumans: true
  briefing:
    text: alien-role-greeting
    color: "#8c3986"
