using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.EntityEffects;
using Content.Trauma.Shared.Tools;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.Tools.UI;

[GenerateTypedNameReferences]
public sealed partial class DebugEffectStickWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<string>? OnSetEffect;

    public DebugEffectStickWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Effects.OnItemSelected += args =>
        {
            var effect = (string?) args.Button.GetItemMetadata(args.Id);
            args.Button.Select(args.Id);
            OnSetEffect?.Invoke(effect);
        };
    }

    public void SetOwner(EntityUid uid)
    {
        if (!_ent.TryGetComponent<DebugEffectStickComponent>(uid, out var comp))
            return;

        var selected = comp.Effect;
        Effects.AddItem("None");
        foreach (var proto in _proto.EnumeratePrototypes<EntityEffectPrototype>())
        {
            var idx = Effects.ItemCount;
            var effect = proto.ID;
            Effects.AddItem(effect);
            Effects.SetItemMetadata(idx, (string?) effect);
            if (effect == selected)
                Effects.Select(idx);
        }
    }
}
