using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Ghost.UI;

// <Trauma>
[GenerateTypedNameReferences]
public sealed partial class GhostroleAlertMenu : FancyWindow
{
    public GhostroleAlertMenu()
    {
        RobustXamlLoader.Load(this);
        ConfirmButton.OnPressed += _ => Close();
    }
}
// <Trauma>
