// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// TODO: Finish scriptures
/// TODO: Make unique page for scriptures
/// TODO: Add favourite scriptures page that will hold 6 scriptures
/// TODO: Unhardcode anything
/// TODO: Clean up remaining shitcode
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ClockWorkSlabWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private EntityUid _owner;

    public ClockWorkSlabWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SectionOne.OnPressed += _ => SetupSection(ClockworkSlabSection.Guide);
        SectionTwo.OnPressed += _ => SetupSection(ClockworkSlabSection.Scriptures);
    }

    private void SetupSection(ClockworkSlabSection section)
    {
        Menu.Visible = false;

        switch (section)
        {
            case ClockworkSlabSection.Guide:
            {
                var guideSection = new CogSlabGuideSection();
                ViewContainer.AddChild(guideSection);
                break;
            }
            case ClockworkSlabSection.Scriptures:
            {
                var scriptureSection = new CogSlabScriptureSection(_owner, _entMan);
                ViewContainer.AddChild(scriptureSection);
                break;
            }
        }
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }
}

public enum ClockworkSlabSection : byte
{
    Guide,
    Scriptures,
}
