// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// Added to second page of <see cref="CogSlabScriptureRecitePage"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabRecitePageContents : BoxContainer
{
    /// <summary>
    /// Notifies BUI that we want to recite.
    /// Passes the event through this order, upwards:
    /// 1. Here
    /// 2. <see cref="CogSlabScriptureRecitePage"/>
    /// 3. <see cref="CogSlabScriptureButton"/>
    /// 4. <see cref="CogSlabScripturePage"/>
    /// 5. <see cref="CogSlabScriptureSection"/>
    /// 6. <see cref="ClockWorkSlabWindow"/>
    /// </summary>
    public event Action<EntProtoId?>? OnRecite;

    public CogSlabRecitePageContents(string? scriptureName, EntProtoId? scripture)
    {
        RobustXamlLoader.Load(this);

        ScriptureName.Text = scriptureName;

        Recite.OnPressed += _ => OnRecite?.Invoke(scripture);
    }

    public CogSlabRecitePageContents()
    {
        RobustXamlLoader.Load(this);
    }
}
