using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// The page displayed after you press <see cref="CogSlabScriptureButton"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScriptureRecitePage : CogSlabPage
{
    private EntProtoId? _scripture;

    public CogSlabScriptureRecitePage(EntProtoId scripture)
    {
        RobustXamlLoader.Load(this);
        _scripture = scripture;

        SetupPage();
    }

    private void SetupPage()
    {
        // First page contains info
        FirstPageContent.Text = "This is some info for you";

        // Second page contains
        // recital button
        // (p2) tiers
        // a picture of the scripture
        // a button to add to favourites

        SecondPageContent.Text = _scripture?.ToString();
    }
}

