// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.ClockworkCult.Scripture;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A <see cref="CogSlabPage"/> that is dedicated to showing entities with <see cref="ScriptureComponent"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScripturePage : CogSlabPage
{
    public event Action<EntProtoId?, string?>? OnRecite;

    /// <summary>
    /// The scriptures that belong to this page.
    /// </summary>
    private List<EntProtoId> _scriptures = new();

    private CogSlabScriptureSection _parent;

    public CogSlabScripturePage(CogSlabScriptureSection parent)
    {
        RobustXamlLoader.Load(this);
        _parent = parent;

        // So they go from top to bottom, and not left to right
        FirstPage.Orientation = LayoutOrientation.Vertical;
        SecondPage.Orientation = LayoutOrientation.Vertical;

        UpdateScriptures();
    }

    private void UpdateScriptures()
    {
        FirstPage.RemoveAllChildren();
        SecondPage.RemoveAllChildren();

        BoxContainer pageToAdd; // The page to add the scriptures, starts at first page
        for (int i = 0; i < _scriptures.Count; i++)
        {
            // We want to spread the scriptures equally to the 2 pages,
            // so we pass the first (_parent.ScripturesPerPage / 2) scriptures to first page then the
            // other scriptures to the second page
            var condition = i < _parent.ScripturesPerPage / 2;
            pageToAdd = condition ? FirstPage : SecondPage;

            var scriptureButton = new CogSlabScriptureButton(_scriptures[i], _parent);
            scriptureButton.OnRecite += (script, tierData) => OnRecite?.Invoke(script, tierData);
            pageToAdd.AddChild(scriptureButton);
        }
    }

    public void AddScripture(EntProtoId scripture)
    {
        _scriptures.Add(scripture);
        UpdateScriptures();
    }
}
