// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.EntityEffects;
using Content.Trauma.Shared.ClockworkCult.Scripture;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// Added to second page of <see cref="CogSlabScriptureRecitePage"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabRecitePageContents : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    /// <summary>
    /// Notifies BUI that we want to recite.
    /// Passes the event through this order, upwards:
    /// 1. Here
    /// 2. <see cref="CogSlabScriptureRecitePage"/>
    /// 3. <see cref="CogSlabScriptureButton"/>
    /// 4. <see cref="CogSlabScripturePage"/>
    /// 5. <see cref="CogSlabScriptureSection"/>
    /// 6. <see cref="ClockWorkSlabWindow"/>
    /// </summary>
    public event Action<EntProtoId?, string?>? OnRecite;

    /// <summary>
    /// For scriptures that support tiers, the current tier selected
    /// </summary>
    private string? _currentDataSelected;

    public CogSlabRecitePageContents(string? scriptureName, EntProtoId? scripture)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ScriptureName.Text = scriptureName;

        if (scripture is not { } scriptureProto)
            return;

        // If we support tiers, then store them as buttons
        if (_proto.Resolve(scriptureProto, out var scriptureResolved)
            && scriptureResolved.TryGetComponent<ScriptureTierComponent>(out var scriptureTier))
        {
            for (int i = 0; i < scriptureTier.Tiers.Count; i++)
            {
                var tierButton = new Button();
                tierButton.Text = $"T{i+1}";
                tierButton.ToolTip = scriptureTier.Tiers[i].Description;

                var currentTier = scriptureTier.Tiers[i];

                tierButton.Disabled = currentTier.Locked;
                tierButton.OnPressed += args => ButtonOnOnPressed(args, currentTier.Id, currentTier.Locked);

                TierContainer.AddChild(tierButton);
            }
        }

        Recite.OnPressed += _ => OnRecite?.Invoke(scripture, _currentDataSelected);
    }

    private void ButtonOnOnPressed(BaseButton.ButtonEventArgs obj, string? tier, bool locked)
    {
        _currentDataSelected = tier;

        // Disable this button and enable the other ones (if they aren't locked).
        foreach (var control in TierContainer.Children)
        {
            if (control is not Button button)
                continue;

            // todo: playtest
            button.Disabled = !locked;
        }

        // Disable our button since we selected it
        if (obj.Button is not Button clickedButton)
            return;

        clickedButton.Disabled = true;
    }

    public CogSlabRecitePageContents()
    {
        RobustXamlLoader.Load(this);
    }
}
