// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.ClockworkCult.Scripture;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// The page displayed after you press <see cref="CogSlabScriptureButton"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScriptureRecitePage : CogSlabPage
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<EntProtoId?, string?>? OnRecite;

    private EntProtoId? _scripture;

    private CogSlabScriptureSection _parent;

    public CogSlabScriptureRecitePage(EntProtoId scripture, CogSlabScriptureSection parent)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _scripture = scripture;
        _parent = parent;

        // Allows us to go back to the Scriptures section, if clicked
        EnableBackButton(true);
        Back.OnPressed += BackOnOnPressed;

        SetupPage();
    }

    private void BackOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _parent.RemovePage(this);
        _parent.EnablePageCounter(true);
        EnableBackButton(false);
    }

    private void SetupPage()
    {
        // First page contains info
        if (_proto.TryIndex(_scripture, out var scripture))
        {
            FirstPageContent.Text = scripture.Description; // TODO: This should be loc, so it can include prices and stuff
        }

        // Second page contains
        // TODO: a picture of the scripture
        // TODO: a button to add to favourites

        var scriptureName = scripture?.Name;
        var contents = new CogSlabRecitePageContents(scriptureName, _scripture);

        contents.OnRecite += (script, tierData) => OnRecite?.Invoke(script, tierData);

        SecondPageContent.AddChild(contents);
    }
}
