// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A <see cref="CogSlabPage"/> that is dedicated to showing entities with <see cref="ScriptureComponent"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScripturePage : CogSlabPage
{
    public event Action<EntProtoId?>? OnRecite;

    /// <summary>
    /// The scriptures that belong to this page.
    /// </summary>
    private List<EntProtoId> _scriptures = new();

    private CogSlabScriptureSection _parent;

    public CogSlabScripturePage(CogSlabScriptureSection parent)
    {
        RobustXamlLoader.Load(this);
        _parent = parent;

        UpdateScriptures();
    }

    private void UpdateScriptures()
    {
        // TODO: Split scriptures to the pages equally
        // TODO: Scriptures should be texturebuttons
        // TODO: Add unique page for scripture details
        FirstPage.RemoveAllChildren();
        foreach (var scripture in _scriptures)
        {
            var scriptureButton = new CogSlabScriptureButton(scripture, _parent);
            scriptureButton.OnRecite += script => OnRecite?.Invoke(script);
            FirstPage.AddChild(scriptureButton);
        }
    }

    public void AddScripture(EntProtoId scripture)
    {
        _scriptures.Add(scripture);
        UpdateScriptures();
    }
}
