using Content.Trauma.Shared.ClockworkCult.Scripture;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

[GenerateTypedNameReferences]
public sealed partial class CogSlabScriptureSection : CogSlabSection
{
    [Dependency] private readonly IEntitySystemManager _system = default!;

    private readonly IEntityManager _entityManager;
    private readonly ScriptureSystem _scripture;

    private readonly EntityQuery<ScriptureContainerComponent> _scriptureContainerQuery;

    private EntityUid _owner;

    /// <summary>
    /// How many scriptures to display per one <see cref="CogSlabPage"/>.
    /// Each "page" of <see cref="CogSlabPage"/> will hold ScripturesPerPage / 2 scriptures.
    /// </summary>
    private int _scripturesPerPage = 6;

    public CogSlabScriptureSection(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entityManager = entMan;
        _owner = owner;

        _scripture = _system.GetEntitySystem<ScriptureSystem>();

        _scriptureContainerQuery = _entityManager.GetEntityQuery<ScriptureContainerComponent>();

        SetupScriptures();
    }

    private void SetupScriptures()
    {
        // Check that our container is not null
        if (!_scriptureContainerQuery.TryComp(_owner, out var scriptureContainer)
            || scriptureContainer.Scriptures is not {} scriptures)
            return;

        // Calculate how many scriptures we have, so we can iterate over the amount
        var scripturesAmount = scriptures.Count;
        Log.Debug($"Adding {scripturesAmount} scriptures.");

        // For every ScripturesPerPage scriptures, create one CogSlabPage
        CogSlabScripturePage? currentPage = null;
        for (var i = 0; i < scripturesAmount; i++)
        {
            if (i % _scripturesPerPage == 0)
            {
                var page = new CogSlabScripturePage();
                currentPage = page;
                AddChild(page);
            }

            // Get the prototype of the scripture, and add it to the current page
            if (_scripture.TryGetScripturePrototype( scriptures.ContainedEntities[i] ) is {} scripturePrototype
                && scripturePrototype is {} scriptureProto
                && currentPage is {} scripturePage)
            {
                Log.Debug("Adding scripture to CogSlabScripturePage...");
                scripturePage.AddScripture(scriptureProto);
            }
        }
    }
}

