using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// Displays the scripture and a button to go to its page.
/// Appears at <see cref="CogSlabScriptureSection"/>, via a <see cref="CogSlabScripturePage"/>.
///
/// TODO: Some scriptures may have quick recital button (if they don't have tiers)
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScriptureButton : BoxContainer
{
    /// <summary>
    /// The scripture that belongs to this button
    /// </summary>
    private EntProtoId _scripture;

    private CogSlabScriptureSection _parent;

    public CogSlabScriptureButton(EntProtoId scripture, CogSlabScriptureSection parent)
    {
        RobustXamlLoader.Load(this);
        _scripture = scripture;
        _parent = parent;

        ScriptureButton.OnPressed += ScriptureButtonOnOnPressed;
    }

    private void ScriptureButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        // TODO: nvm this should be a separate section
        var recitePage = new CogSlabScriptureRecitePage(_scripture);
        _parent.AddPage(recitePage);
        _parent.DisplayPage(recitePage);
    }
}

