// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Text;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A CogSlabSection houses a certain amount of <see cref="CogSlabPage"/>
/// A section supports turning a page (left, right) and going back to the main window of Clockwork Slab
/// </summary>
[GenerateTypedNameReferences]
public abstract partial class CogSlabSection : Control
{
    /// <summary>
    /// Each section has a list of pages, which are dynamically added
    /// </summary>
    private List<CogSlabPage> _cogSlabPages = new();

    /// <summary>
    /// The current page in view
    /// </summary>
    private int _currentPage;

    /// <summary>
    /// Whether we are on the first page of the section
    /// </summary>
    private bool IsFirstPage => _currentPage == 0;

    /// <summary>
    ///  Whether we are on the last page of the section
    /// </summary>
    private bool IsLastPage => _currentPage >= _cogSlabPages.Count - 1;

    public CogSlabSection()
    {
        RobustXamlLoader.Load(this);

        PrevButton.OnPressed += _ => GoPreviousPage();
        NextButton.OnPressed += _ => GoNextPage();

        UpdateSection();
    }

    /// <summary>
    /// Displays a specific page from <see cref="_cogSlabPages"/>
    /// </summary>
    public void DisplayPage(CogSlabPage page)
    {
        if (!_cogSlabPages.Contains(page))
            return;

        _currentPage = _cogSlabPages.IndexOf(page);
        UpdateSection();
    }

    /// <summary>
    /// Toggles the visibility of buttons
    /// </summary>
    /// <param name="enabled"></param>
    public void ToggleButtons(bool enabled)
    {
        NextButton.Visible = enabled;
        PrevButton.Visible = enabled;
    }

    public void EnablePageCounter(bool enabled)
    {
        PageCounter.Visible = enabled;
    }

    /// <summary>
    /// Adds a page to <see cref="_cogSlabPages"/> and updates the ui.
    /// </summary>
    public void AddPage(CogSlabPage page)
    {
        _cogSlabPages.Add(page);
        UpdateSection();
    }

    /// <summary>
    /// Removes a page from <see cref="_cogSlabPages"/> and updates the ui.
    /// </summary>
    public void RemovePage(CogSlabPage page)
    {
        _cogSlabPages.Remove(page);
        _currentPage = 0;
        UpdateSection();
    }

    /// <summary>
    /// Turns to the next/previous page, and updates the ui.
    /// </summary>
    /// <param name="number"></param> How many pages to turn, and in which direction (if negative)
    public void TurnPage(int number)
    {
        _currentPage = Math.Clamp(_currentPage + number, 0, _cogSlabPages.Count - 1);
        UpdateSection();
    }

    private void UpdateSection()
    {
        // The page holder holds the current page displayed, so we clear them
        PageHolder.RemoveAllChildren();

        if (_cogSlabPages.Count == 0)
            return;

        var pageToDisplay = _cogSlabPages[_currentPage];
        PageHolder.AddChild(pageToDisplay);

        // In order to show how many pages are left to the user
        PageCounter.Text = $"{_currentPage + 1} | {_cogSlabPages.Count}";

        // Whether we can display the buttons
        var visibilityCheck = _cogSlabPages.Count > 1;

        PrevButton.Visible = visibilityCheck;
        NextButton.Visible = visibilityCheck;

        PrevButton.Disabled = IsFirstPage;
        NextButton.Disabled = IsLastPage;
    }

    private void GoNextPage() =>
        TurnPage(1);

    private void GoPreviousPage() =>
        TurnPage(-1);

    /// <summary>
    /// We automatically register new cogslabpages added to the ui
    /// </summary>
    protected override void ChildAdded(Control child)
    {
        base.ChildAdded(child);

        if (child is CogSlabPage page && child.Parent != PageHolder)
        {
            if (page.Parent == this)
                RemoveChild(page);

            _cogSlabPages.Add(page);
            UpdateSection();
        }
    }
}
