// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A CogSlabPage tries to mimic how actual books look like, with 2 paper pages and a seperator in the middle.
/// CogSlabPages are used by <see cref="CogSlabSection"/>
/// </summary>
[GenerateTypedNameReferences]
public abstract partial class CogSlabPage : BoxContainer
{
    /// <summary>
    /// The title of the page
    /// </summary>
    public string? PageTitleText
    {
        get => PageTitle.Text;
        set => PageTitle.Text = value;
    }

    /// <summary>
    /// The text content of the first page
    /// </summary>
    public string? FirstPageContentText
    {
        get => FirstPageContent.Text;
        set => FirstPageContent.Text = value;
    }

    /// <summary>
    /// The text content of the second page
    /// </summary>
    public string? SecondPageContentText
    {
        get => SecondPageContent.Text;
        set => SecondPageContent.Text = value;
    }

    public CogSlabPage()
    {
        RobustXamlLoader.Load(this);
    }

    public void EnableBackButton(bool enabled)
    {
        Back.Visible = enabled;
    }
}
