// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// The page displayed after you press <see cref="CogSlabScriptureButton"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScriptureRecitePage : CogSlabPage
{
    public event Action<EntProtoId?>? OnRecite;

    private EntProtoId? _scripture;

    private CogSlabScriptureSection _parent;

    public CogSlabScriptureRecitePage(EntProtoId scripture, CogSlabScriptureSection parent)
    {
        RobustXamlLoader.Load(this);
        _scripture = scripture;
        _parent = parent;

        // Allows us to go back to the Scriptures section, if clicked
        EnableBackButton(true);
        Back.OnPressed += BackOnOnPressed;

        SetupPage();
    }

    private void BackOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _parent.RemovePage(this);
        _parent.EnablePageCounter(true);
        EnableBackButton(false);
    }

    private void SetupPage()
    {
        // First page contains info
        FirstPageContent.Text = "This is some info for you";

        // Second page contains
        // recital button
        // (p2) tiers
        // a picture of the scripture
        // a button to add to favourites

        var scriptureName = _scripture?.ToString();
        var contents = new CogSlabRecitePageContents(scriptureName, _scripture);

        contents.OnRecite += script => OnRecite?.Invoke(script);

        SecondPageContent.AddChild(contents);
    }
}
