// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A <see cref="CogSlabPage"/> that is used for pure text only purposes.
/// TODO: Move the richtextlabels from CogSlabPage in this xaml by c#
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabTextPage : CogSlabPage
{
    public CogSlabTextPage()
    {
        RobustXamlLoader.Load(this);
    }
}
