// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A <see cref="CogSlabPage"/> that is dedicated to showing entities with <see cref="ScriptureComponent"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabScripturePage : CogSlabPage
{
    /// <summary>
    /// The scriptures that belong to this page.
    /// </summary>
    private List<EntProtoId> _scriptures = new();

    public CogSlabScripturePage()
    {
        RobustXamlLoader.Load(this);

        UpdateScriptures();
    }

    private void UpdateScriptures()
    {
        // TODO: Split scriptures to the pages equally
        // TODO: Scriptures should be texturebuttons
        // TODO: Add unique page for scripture details
        FirstPage.RemoveAllChildren();
        foreach (var scripture in _scriptures)
        {
            var label = new Label();
            label.Text = "this is a test";
            label.Align = Label.AlignMode.Center;
            label.SetSize = new Vector2(60, 60);
            FirstPage.AddChild(label);
        }
    }

    public void AddScripture(EntProtoId scripture)
    {
        _scriptures.Add(scripture);
        UpdateScriptures();
    }
}
