// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.RoundEndCredits;

[GenerateTypedNameReferences]
public sealed partial class EndRoundCreditsControl : ScrollContainer
{
    public EndRoundCreditsControl()
    {
        RobustXamlLoader.Load(this);
    }
}
