using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.CosmicCult.Prototypes;
using Content.Shared._DV.CosmicCult;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.CosmicCult.UI.CosmicShop;

[GenerateTypedNameReferences]
public sealed partial class CosmicShopMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    // All influence prototypes
    private readonly IEnumerable<InfluencePrototype> _influencePrototypes;
    public Action<ProtoId<InfluencePrototype>>? OnGainButtonPressed;
    public Action? OnLevelUpConfirmed;
    private InfluencePrototype? SelectedInfluence = null;

    public CosmicShopMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _influencePrototypes = _proto.EnumeratePrototypes<InfluencePrototype>();
        LevelUpConfirm.OnPressed += _ => OnLevelUpConfirmed?.Invoke();

        CultProgressBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(15, 17, 30) };
        CultProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(91, 62, 124) };
    }

    public void UpdateState(CosmicShopBuiState state)
    {
        UpdateBar(state);
        UpdateEntropy(state);
        UpdateInfluences(state);
        UpdateLevelupConfirmation(state);
        if (SelectedInfluence is { } influence) OpenInfluenceDetails(influence, state);
    }

    /// <summary>
    ///     Updates the progress bar
    /// </summary>
    private void UpdateBar(CosmicShopBuiState state)
    {
        var percentComplete = 100f * ((float) state.CurrentProgress / state.TargetProgress);

        percentComplete = Math.Min(percentComplete, 100f);

        if (state.EntropyLocked) percentComplete = 100f;

        CultProgressBar.Value = percentComplete;

        ProgressBarPercentage.Text = Loc.GetString("cosmic-shop-interface-progress-bar", ("percentage", percentComplete.ToString("0")));
    }

    /// <summary>
    ///     Updates the entropy fields
    /// </summary>
    private void UpdateEntropy(CosmicShopBuiState state)
    {
        var entropyToNextStage = Math.Max(state.TargetProgress - state.CurrentProgress, 0);

        if (state.EntropyLocked) entropyToNextStage = 0;

        AvailableEntropy.Text = Loc.GetString("cosmic-shop-interface-entropy-value", ("infused", state.EntropyBudget));
        EntropyUntilNextStage.Text = Loc.GetString("cosmic-shop-interface-entropy-value", ("infused", entropyToNextStage));
        CultisttUntilNextCultStage.Text = state.CultistsForNextLevel.ToString();
    }

    /// <summary>
    ///    Update all the influence thingies
    /// </summary>
    private void UpdateInfluences(CosmicShopBuiState state)
    {
        var influenceButtons = new List<InfluenceButtonContainer>();
        foreach (var influenceProto in _influencePrototypes)
        {
            var uiBoxState = GetUIBoxStateForInfluence(influenceProto, state);
            var influenceButton = new InfluenceButtonContainer(influenceProto, uiBoxState);
            influenceButton.OnDetailButtonPressed += () => OpenInfluenceDetails(influenceProto, state);
            influenceButtons.Add(influenceButton);
        }

        Control[] containers = [Level0, Level1, Level2, Level3];
        foreach (var container in containers)
            container.RemoveAllChildren();
        foreach (var box in influenceButtons.OrderBy(box => box.Proto.Cost))
            containers[box.Proto.Tier].AddChild(box);
    }

    private void UpdateLevelupConfirmation(CosmicShopBuiState state)
    {
        LevelUpConfirmation.Visible = state.LevelUpAwaitingConfirmation;
        if (!state.LevelUpAwaitingConfirmation) return;
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequences"));
        msg.PushNewline();
        msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequence-level" + (state.CurrentLevel + 1).ToString()));
        if ( state.CultistsForNextLevel <= 1 && state.CurrentLevel == state.CurrentTier) // Tierup on normal conditions
        {
            msg.PushNewline();
            msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequence-tier" + (state.CurrentTier + 1).ToString()));
        }
        if (state.CurrentLevel > state.CurrentTier) // Speedrun tierup
        {
            msg.PushNewline();
            msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequence-tier" + (state.CurrentLevel).ToString()));
        }
        ConsequenceLabel.SetMessage(msg, Color.FromHex("#4CA7AD"));
    }

    /// <summary>
    ///    Show all the details of the selected influence
    /// </summary>
    private void OpenInfluenceDetails(InfluencePrototype influenceProto, CosmicShopBuiState state)
    {
        SelectedInfluence = influenceProto;
        InfluenceInfoContainer.RemoveAllChildren();
        var uiBoxState = GetUIBoxStateForInfluence(influenceProto, state);
        var influenceBox = new InfluenceUIBox(influenceProto, uiBoxState);
        InfluenceInfoContainer.AddChild(influenceBox);
        influenceBox.OnGainButtonPressed += () => OnGainButtonPressed?.Invoke(influenceProto.ID);
    }

    private InfluenceUIBox.InfluenceUIBoxState GetUIBoxStateForInfluence(InfluencePrototype influence, CosmicShopBuiState state)
    {

        var unlocked = state.UnlockedInfluences.Contains(influence.ID);
        var owned = state.OwnedInfluences.Contains(influence);

        //more verbose than it needs to be, but it reads nicer
        if (owned)
            return InfluenceUIBox.InfluenceUIBoxState.Owned;

        //TODO: dependency check when skill trees are real

        //if it's unlocked, do we have enough entropy to buy it?
        if (unlocked)
            return influence.Cost > state.EntropyBudget
                ? InfluenceUIBox.InfluenceUIBoxState.UnlockedAndNotEnoughEntropy
                : InfluenceUIBox.InfluenceUIBoxState.UnlockedAndEnoughEntropy;

        return InfluenceUIBox.InfluenceUIBoxState.Locked;
    }
}
