using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.CosmicCult.Prototypes;
using Content.Shared._DV.CosmicCult;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.CosmicCult.UI.CosmicShop;

[GenerateTypedNameReferences]
public sealed partial class CosmicShopMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    // All influence prototypes
    private readonly IEnumerable<InfluencePrototype> _influencePrototypes;
    public Action<ProtoId<InfluencePrototype>>? OnGainButtonPressed;
    public Action? OnLevelUpConfirmed;
    private InfluencePrototype? SelectedInfluence = null;

    public CosmicShopMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _influencePrototypes = _proto.EnumeratePrototypes<InfluencePrototype>();
        LevelUpConfirm.OnPressed += _ => OnLevelUpConfirmed?.Invoke();

        CultProgressBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(15, 17, 30) };
        CultProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(91, 62, 124) };
    }

    public void UpdateState(CosmicShopBuiState state)
    {
        UpdateBar(state);
        UpdateEntropy(state);
        UpdateInfluences(state);
        LevelUpConfirmation.Visible = state.LevelUpAwaitingConfirmation;
        if (SelectedInfluence is { } influence) OpenInfluenceDetails(influence, state);
    }

    /// <summary>
    ///     Updates the progress bar
    /// </summary>
    private void UpdateBar(CosmicShopBuiState state)
    {
        var percentComplete = 100f * ((float) state.CurrentProgress / state.TargetProgress);

        percentComplete = Math.Min(percentComplete, 100f);

        if (state.EntropyLocked) percentComplete = 100f;

        CultProgressBar.Value = percentComplete;

        ProgressBarPercentage.Text = Loc.GetString("cosmic-shop-interface-progress-bar", ("percentage", percentComplete.ToString("0")));
    }

    /// <summary>
    ///     Updates the entropy fields
    /// </summary>
    private void UpdateEntropy(CosmicShopBuiState state)
    {
        var entropyToNextStage = Math.Max(state.TargetProgress - state.CurrentProgress, 0);

        if (state.EntropyLocked) entropyToNextStage = 0;

        AvailableEntropy.Text = Loc.GetString("cosmic-shop-interface-entropy-value", ("infused", state.EntropyBudget));
        EntropyUntilNextStage.Text = Loc.GetString("cosmic-shop-interface-entropy-value", ("infused", entropyToNextStage));
        CultisttUntilNextCultStage.Text = state.CultistsForNextLevel.ToString();
    }

    /// <summary>
    ///    Update all the influence thingies
    /// </summary>
    private void UpdateInfluences(CosmicShopBuiState state)
    {
        var influenceButtons = new List<InfluenceButtonContainer>();
        foreach (var influenceProto in _influencePrototypes)
        {
            var uiBoxState = GetUIBoxStateForInfluence(influenceProto, state);
            var influenceButton = new InfluenceButtonContainer(influenceProto, uiBoxState);
            influenceButton.OnDetailButtonPressed += () => OpenInfluenceDetails(influenceProto, state);
            influenceButtons.Add(influenceButton);
        }

        // Yes this is shitcode. No I don't care. I will be replacing it anyway when I implement skill trees. Which will be even worse, because nothing is nice in UI.
        Level3.RemoveAllChildren();
        Level2.RemoveAllChildren();
        Level1.RemoveAllChildren();
        Level0.RemoveAllChildren();
        foreach (var box in influenceButtons.OrderBy(box => box.Proto.ID))
            switch (box.Proto.Tier)
            {
                case 3:
                    Level3.AddChild(box);
                    break;
                case 2:
                    Level2.AddChild(box);
                    break;
                case 1:
                    Level1.AddChild(box);
                    break;
                case 0:
                    Level0.AddChild(box);
                    break;
            }
    }

    /// <summary>
    ///    Show all the details of the selected influence
    /// </summary>
    private void OpenInfluenceDetails(InfluencePrototype influenceProto, CosmicShopBuiState state)
    {
        SelectedInfluence = influenceProto;
        InfluenceInfoContainer.RemoveAllChildren();
        var uiBoxState = GetUIBoxStateForInfluence(influenceProto, state);
        var influenceBox = new InfluenceUIBox(influenceProto, uiBoxState);
        InfluenceInfoContainer.AddChild(influenceBox);
        influenceBox.OnGainButtonPressed += () => OnGainButtonPressed?.Invoke(influenceProto.ID);
    }

    private InfluenceUIBox.InfluenceUIBoxState GetUIBoxStateForInfluence(InfluencePrototype influence, CosmicShopBuiState state)
    {

        var unlocked = state.UnlockedInfluences.Contains(influence.ID);
        var owned = state.OwnedInfluences.Contains(influence);

        //more verbose than it needs to be, but it reads nicer
        if (owned)
            return InfluenceUIBox.InfluenceUIBoxState.Owned;

        //TODO: dependency check when skill trees are real

        //if it's unlocked, do we have enough entropy to buy it?
        if (unlocked)
            return influence.Cost > state.EntropyBudget
                ? InfluenceUIBox.InfluenceUIBoxState.UnlockedAndNotEnoughEntropy
                : InfluenceUIBox.InfluenceUIBoxState.UnlockedAndEnoughEntropy;

        return InfluenceUIBox.InfluenceUIBoxState.Locked;
    }
}
