// SPDX-License-Identifier: AGPL-3.0-or-later
using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Genetics.Console;
using Content.Trauma.Shared.Genetics.Mutations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticsScannerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly ScannedGenomeSystem _genome;

    public event Action? OnScan;

    private EntityQuery<GeneticsScannerComponent> _query;

    public GeneticsScannerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _genome = _entMan.System<ScannedGenomeSystem>();

        _query = _entMan.GetEntityQuery<GeneticsScannerComponent>();

        Sequencer.MakeReadonly();
        Sequencer.OnScan += () => OnScan?.Invoke();

        Sequencer.UpdateHasScanner(true); // this is the scanner
    }

    private EntityUid _uid;
    private EntityUid? _mob;
    private bool _busy;
    private bool _scanned;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_query.TryComp(_uid, out var comp))
            Update(comp);
    }

    public void SetEntity(EntityUid uid)
    {
        if (!_query.TryComp(uid, out var comp))
            return;

        _uid = uid;
        Update(comp);
    }

    public void UpdateState(GeneticsConsoleState state)
    {
        Sequencer.SetState(state.Sequences);
    }

    private void Update(GeneticsScannerComponent comp)
    {
        if (comp.ScannedMob != _mob)
            UpdateMob(_mob = comp.ScannedMob);
        if (comp.Busy != _busy)
            Sequencer.SetBusy(_busy = comp.Busy);
    }

    private void UpdateMob(EntityUid? mob)
    {
        Sequencer.SetMob(mob);
        if (mob is not {} uid)
            return;

        var scanned = _genome.IsScanned(uid);
        if (scanned != _scanned)
        {
            _scanned = scanned;
            Sequencer.UpdateScanButton();
        }
    }
}
