using Content.Trauma.Shared.Genetics.Console;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticStorage : BoxContainer
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<uint>? OnPrint;

    private Entity<GeneticsDiskComponent>? _disk;
    private bool _cooldown;
    private List<Button> _buttons = new();

    public GeneticStorage()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetConsole(GeneticsConsoleComponent comp)
    {
        _buttons.Clear();
        PrintButtons.RemoveAllChildren();
        for (var i = 0; i < comp.Prints.Count; i++)
        {
            var index = (uint) i;
            var delay = comp.Prints[i].Delay.TotalSeconds;
            var proto = comp.Prints[i].Proto;
            var button = new Button()
            {
                Text = Loc.GetString("genetics-console-print-item", ("item", _proto.Index(proto).Name), ("delay", delay)),
                MaxWidth = 120f,
                Margin = new Thickness(4),
                HorizontalExpand = true
            };
            button.OnPressed += _ => OnPrint?.Invoke(index);
            _buttons.Add(button);
            PrintButtons.AddChild(button);
        }
    }

    public void UpdateDisk(Entity<GeneticsDiskComponent>? disk)
    {
        _disk = disk;
        // TODO
        DiskName.Text = _entMan.GetComponentOrNull<MetaDataComponent>(disk)?.EntityName
            ?? Loc.GetString("genetics-console-no-disk");
        MutationName.Text = _proto.TryIndex(disk?.Comp.Mutation, out var proto)
            ? proto.Name
            : Loc.GetString("genetics-console-disk-empty");
        UpdateCooldowns(_cooldown);
    }

    public void UpdateCooldowns(bool cooldown)
    {
        _cooldown = cooldown;
        var disabled = cooldown || _disk == null;
        foreach (var button in _buttons)
        {
            button.Disabled = disabled;
        }
    }
}
