using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GenePuzzle : Control
{
    public event Action<uint, char>? OnSetBase;
    public event Action? OnJoker;
    public event Action? OnSequence;

    private bool _busy;
    private bool _sequenced;
    private string _bases = string.Empty;

    public GenePuzzle()
    {
        RobustXamlLoader.Load(this);

        JokerButton.OnPressed += _ => OnJoker?.Invoke();
        SequenceButton.OnPressed += _ => OnSequence?.Invoke();
        OnSetBase += (_, _) => UpdateSequenceButton();
    }

    private void UpdateSequenceButton()
    {
        SequenceButton.Disabled = _busy || _sequenced || !IsComplete();
    }

    private bool IsComplete()
    {
        foreach (var c in _bases)
        {
            if (c == 'X') return false;
        }

        return true;
    }

    public void SetBusy(bool busy)
    {
        _busy = busy;
        UpdateSequenceButton();
    }

    public void SetSequenced(bool sequenced)
    {
        _sequenced = sequenced;
        UpdateSequenceButton();
    }

    public void SetBases(string bases)
    {
        Visible = true;
        _bases = bases;
        BaseButtons.RemoveAllChildren();
        for (int i = 0; i < bases.Length; i++)
        {
            AddBase((uint) i, bases[i]);
        }
        UpdateSequenceButton();
    }

    private void AddBase(uint i, char b)
    {
        var button = new Button();
        button.Text = b.ToString();
        // TODO: implement ctrl / right click
        button.OnPressed += _ =>
        {
            b = Cycle(b);
            button.Text = b.ToString();
            OnSetBase?.Invoke(i, b);
        };
        BaseButtons.AddChild(button);
    }

    private static char Cycle(char b)
        => b switch
        {
            'A' => 'C',
            'C' => 'G',
            'G' => 'T',
            'T' => 'X',
            'X' => 'A',
            _ => b // how
        };
}
