using Content.Trauma.Shared.Genetics.Mutations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Genetics.UI;

/// <summary>
/// Error section to show when the console doesn't have a scanned mob.
/// Includes a scan button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GeneticScanner : BoxContainer
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly ScannedGenomeSystem _genome;

    public event Action? OnScan;
    public event Action<LocId?>? OnErrorSet;

    private EntityUid? _mob;
    private bool _busy;

    public GeneticScanner()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _genome = _entMan.System<ScannedGenomeSystem>();

        ScanButton.OnPressed += _ => OnScan?.Invoke();
    }

    public void SetMob(EntityUid? mob)
    {
        _mob = mob;
        if (mob is not {} uid)
        {
            SetError("genetics-console-sequencer-no-subject");
            ScanButton.Disabled = true;
            return;
        }

        UpdateScanButton(uid);
    }

    public void SetBusy(bool busy)
    {
        _busy = busy;
        if (busy)
        {
            ScanButton.Disabled = true;
            return;
        }

        if (_mob is not {} mob)
            return;

        UpdateScanButton(mob);
    }

    public void UpdateScanButton(EntityUid mob)
    {
        var isScanned = _genome.IsScanned(mob);
        ScanButton.Disabled = isScanned || _busy;
        if (!isScanned)
        {
            SetError("genetics-console-sequencer-not-scanned");
            return;
        }

        SetError(null);
    }

    public void SetError(LocId? error)
    {
        Visible = error != null;
        if (error is {} id)
            ErrorLabel.Text = Loc.GetString(id);
        OnErrorSet?.Invoke(error);
    }
}
