using Content.Client.UserInterface.Controls;
using Content.Shared.Damage;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Mobs.Components;
using Content.Trauma.Shared.Genetics.Console;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticsConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action? OnScan;
    public event Action<uint, uint, char>? OnSetBase;
    public event Action<uint>? OnWriteMutation;
    public event Action<uint>? OnJoker;
    public event Action<uint>? OnSequence;

    private static readonly ProtoId<DamageGroupPrototype> Genetic = "Genetic";

    private EntityQuery<DamageableComponent> _damageableQuery;
    private EntityQuery<GeneticsConsoleComponent> _query;
    private EntityQuery<MobStateComponent> _mobQuery;

    private EntityUid _uid;
    private bool? _hasScanner;
    private EntityUid? _mob;
    private bool _busy;

    public GeneticsConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _damageableQuery = _entMan.GetEntityQuery<DamageableComponent>();
        _query = _entMan.GetEntityQuery<GeneticsConsoleComponent>();
        _mobQuery = _entMan.GetEntityQuery<MobStateComponent>();

        Sequencer.OnScan += () => OnScan?.Invoke();
        Sequencer.OnSetBase += (s, i, b) => OnSetBase?.Invoke(s, i, b);
        Sequencer.OnWriteMutation += i => OnWriteMutation?.Invoke(i);
        Sequencer.OnJoker += i => OnJoker?.Invoke(i);
        Sequencer.OnSequence += i => OnSequence?.Invoke(i);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_query.TryComp(_uid, out var comp))
        {
            Close();
            return;
        }

        Update(comp);
    }

    public void SetEntity(EntityUid uid)
    {
        if (!_query.TryComp(uid, out var comp))
            return;

        _uid = uid;
        Update(comp);
    }

    public void UpdateState(GeneticsConsoleState state)
    {
        // TODO
        Sequencer.SetState(state.Sequences);
    }

    private void Update(GeneticsConsoleComponent comp)
    {
        var hasScanner = comp.Scanner != null;
        if (hasScanner != _hasScanner)
        {
            _hasScanner = hasScanner;
            UpdateScanner(hasScanner);
        }
        if (comp.ScannedMob != _mob)
            UpdateMob(_mob = comp.ScannedMob);
        if (comp.Busy != _busy)
            UpdateBusy(_busy = comp.Busy);
    }

    private void UpdateScanner(bool hasScanner)
    {
        UpdateMob(hasScanner ? _mob : null);
        if (!hasScanner)
            MobStatus.Text = Loc.GetString("genetics-console-no-scanner");
    }

    private void UpdateMob(EntityUid? uid)
    {
        MobView.SetEntity(uid);
        Sequencer.SetMob(uid);
        if (_mobQuery.TryComp(uid, out var mob))
        {
            MobName.Text = _entMan.GetComponent<MetaDataComponent>(uid.Value).EntityName;
            MobStatus.Text = Loc.GetString($"mob-state-{mob.CurrentState}");
            MobIntegrity.Text = GetGeneticDamage(uid.Value) is {} damage
                ? Math.Max(100 - damage, 0).ToString()
                : Loc.GetString("generic-not-available-shorthand");
        }
        else
        {
            MobName.Text = Loc.GetString("genetics-console-no-subject");
            MobStatus.Text = Loc.GetString("generic-not-available-shorthand");
            MobIntegrity.Text = Loc.GetString("generic-not-available-shorthand");
        }
    }

    private void UpdateBusy(bool busy)
    {
        Sequencer.SetBusy(busy);
    }

    private int? GetGeneticDamage(EntityUid mob)
    {
        if (!_damageableQuery.TryComp(mob, out var comp))
            return null;

        if (!comp.DamagePerGroup.TryGetValue(Genetic, out var damage))
            return 0;

        return (int) damage;
    }
}
