using Content.Client.Resources;
using Content.Trauma.Shared.Genetics.Console;
using Content.Trauma.Shared.Genetics.Mutations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ResourceManagement;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticSequencer : Control
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IResourceCache _cache = default!;
    private readonly MutationSystem _mutation;

    public event Action? OnScan;
    public event Action<uint?>? OnSelectSequence;
    public event Action<uint, uint, char>? OnSetBase;
    public event Action<uint>? OnWriteMutation;
    public event Action<uint>? OnJoker;
    public event Action<uint>? OnSequence;

    private EntityQuery<ScannedGenomeComponent> _scannedQuery;
    private EntityUid? _mob;
    private bool _busy;

    public GeneticSequencer()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _mutation = _entMan.System<MutationSystem>();
        _scannedQuery = _entMan.GetEntityQuery<ScannedGenomeComponent>();

        Puzzle.OnSetBase += (i, b) =>
        {
            if (SequenceButtons.Index is {} s)
                OnSetBase?.Invoke(s, i, b);
        };
        Puzzle.OnJoker += () =>
        {
            if (SequenceButtons.Index is {} s)
                OnJoker?.Invoke(s);
        };
        Puzzle.OnSequence += () =>
        {
            if (SequenceButtons.Index is {} s)
                OnSequence?.Invoke(s);
        };

        ScanButton.OnPressed += _ => OnScan?.Invoke();
        WriteButton.OnPressed += _ =>
        {
            if (SequenceButtons.Index is {} s)
                OnWriteMutation?.Invoke(s);
        };

        SequenceButtons.OnSelected += i =>
        {
            UpdateSequence();
            OnSelectSequence?.Invoke(i);
        };
    }

    public void SetMob(EntityUid? mob)
    {
        _mob = mob;
        if (mob is not {} uid)
        {
            SetError("genetics-console-sequencer-no-subject");
            ScanButton.Disabled = true;
            return;
        }

        UpdateScanButton(uid);
    }

    private void UpdateScanButton(EntityUid mob)
    {
        var isScanned = _scannedQuery.HasComp(mob);
        ScanButton.Disabled = isScanned || _busy;
        if (!isScanned)
        {
            SetError("genetics-console-sequencer-not-scanned");
            return;
        }

        SetError(null);
    }

    public void SetBusy(bool busy)
    {
        _busy = busy;
        Puzzle.SetBusy(busy);
        if (busy)
        {
            ScanButton.Disabled = true;
            return;
        }

        if (_mob is not {} mob)
            return;

        UpdateScanButton(mob);
    }

    private void UpdateSequence()
    {
        SequenceInfo.Visible = SequenceButtons.Index != null;
        NoSequence.Visible = !SequenceInfo.Visible;
        Puzzle.Visible = SequenceInfo.Visible;
        if (SequenceButtons.Sequence is not {} sequence)
            return;

        Puzzle.SetSequenced(sequence.Mutation != null);
        if (sequence.Mutation is {} id)
        {
            var proto = _proto.Index<EntityPrototype>(id);
            var instability = _mutation.AllMutations[id].Instability;
            MutationName.Text = proto.Name;
            MutationDesc.Text = proto.Description;
            MutationInstability.Text = instability.ToString();
        }
        else
        {
            MutationName.Text = Loc.GetString("genetics-console-mutation-name-placeholder", ("number", sequence.Number));
            MutationDesc.Text = Loc.GetString("generic-unknown-title");
            MutationInstability.Text = Loc.GetString("generic-unknown-title");
        }

        Puzzle.SetBases(sequence.Bases);
    }

    private void SetError(LocId? error)
    {
        MobContainer.Visible = error == null;
        ErrorContainer.Visible = error != null;
        if (error is {} id)
            ErrorLabel.Text = Loc.GetString(id);
    }

    public void SetState(List<SequenceState> states)
    {
        SequenceButtons.SetStates(states);
        var scanned = _mob != null && _scannedQuery.HasComp(_mob);
        if (states.Count == 0 && scanned)
        {
            SetError("genetics-console-sequencer-no-sequences");
            return;
        }

        if (scanned)
            SetError(null);

        SequenceButtons.UpdateSequences();
        UpdateSequence();
    }
}
