using Content.Client.Resources;
using Content.Trauma.Shared.Genetics.Console;
using Content.Trauma.Shared.Genetics.Mutations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Trauma.Client.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticSequencer : Control
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly ScannedGenomeSystem _genome;

    public event Action? OnScan;
    public event Action<uint, uint, char>? OnSetBase;
    public event Action<uint>? OnWriteMutation;
    public event Action<uint>? OnJoker;
    public event Action<uint>? OnSequence;

    private EntityUid? _mob;
    private Entity<GeneticsDiskComponent>? _disk;
    private bool _busy;
    private bool _writeCooldown;

    public GeneticSequencer()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _genome = _entMan.System<ScannedGenomeSystem>();

        Puzzle.OnSetBase += (i, b) =>
        {
            if (SequenceButtons.Index is {} s)
                OnSetBase?.Invoke(s, i, b);
        };
        Puzzle.OnJoker += () =>
        {
            if (SequenceButtons.Index is {} s)
                OnJoker?.Invoke(s);
        };
        Puzzle.OnSequence += () =>
        {
            if (SequenceButtons.Index is {} s)
                OnSequence?.Invoke(s);
        };

        ScanButton.OnPressed += _ => OnScan?.Invoke();
        WriteButton.OnPressed += _ =>
        {
            if (SequenceButtons.Index is {} s)
                OnWriteMutation?.Invoke(s);
        };

        SequenceButtons.OnSelected += i =>
        {
            UpdateSequence();
            UpdateWriteButton();
        };
    }

    public void SetMob(EntityUid? mob)
    {
        _mob = mob;
        if (mob is not {} uid)
        {
            SetError("genetics-console-sequencer-no-subject");
            ScanButton.Disabled = true;
            return;
        }

        UpdateScanButton(uid);
    }

    private void UpdateScanButton(EntityUid mob)
    {
        var isScanned = _genome.IsScanned(mob);
        ScanButton.Disabled = isScanned || _busy;
        if (!isScanned)
        {
            SetError("genetics-console-sequencer-not-scanned");
            return;
        }

        SetError(null);
    }

    public void SetBusy(bool busy)
    {
        _busy = busy;
        Puzzle.SetBusy(busy);
        if (busy)
        {
            ScanButton.Disabled = true;
            return;
        }

        if (_mob is not {} mob)
            return;

        UpdateScanButton(mob);
    }

    private void UpdateSequence()
    {
        Info.Update(SequenceButtons);
        NoSequence.Visible = !Info.Visible;
        Puzzle.Visible = Info.Visible;

        if (SequenceButtons.Sequence is not {} sequence)
            return;

        Puzzle.SetSequenced(sequence.Mutation != null);
        Puzzle.SetBases(sequence.Bases);
    }

    private void SetError(LocId? error)
    {
        MobContainer.Visible = error == null;
        ErrorContainer.Visible = error != null;
        if (error is {} id)
            ErrorLabel.Text = Loc.GetString(id);
    }

    public void SetState(List<SequenceState> states)
    {
        SequenceButtons.SetStates(states);
        var scanned = _mob is {} mob && _genome.IsScanned(mob);
        if (states.Count == 0 && scanned)
        {
            SetError("genetics-console-sequencer-no-sequences");
            return;
        }

        if (scanned)
            SetError(null);

        SequenceButtons.UpdateSequences();
        UpdateSequence();
    }

    public void UpdateDisk(Entity<GeneticsDiskComponent>? disk)
    {
        _disk = disk;
        UpdateWriteButton();
    }

    public void UpdateWriteCooldown(bool cooldown)
    {
        _writeCooldown = cooldown;
        UpdateWriteButton();
    }

    private void UpdateWriteButton()
    {
        WriteButton.Disabled = _disk == null ||
            SequenceButtons.Sequence?.Mutation == null ||
            _writeCooldown;
    }
}
