// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.MobClass;

[GenerateTypedNameReferences]
public sealed partial class MobClassSelectorWindow : FancyWindow
{
    public MobClassSelectorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
