- type: latheRecipePack
  id: TraumaSecurityWeapons
  recipes:
  - PolymerBaton
  - SpearTelescopic
  - WeaponBillyClub
  - WeaponLaserSidearm

- type: latheRecipePack
  id: TraumaMechParts
  recipes:
  - EDHead
  - EDLegL
  - EDLegR
  - EDShell
  - ED209Endoskeleton
  - EDAiCoreElectronics
  - EDIFFElectronics
  - EDWeaponControlsElectronics

- type: latheRecipePack
  id: SecurityAmmoTrauma
  recipes:
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  - BoxShellTranquilizer
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxPistolHoly
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleUranium
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazineRifleIncendiary
  - MagazineRifleUranium
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium