// SPDX-License-Identifier: AGPL-3.0-or-later
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Medical.Client.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
