using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;

namespace Content.Trauma.Client.Bank.Ui;

[GenerateTypedNameReferences]
public sealed partial class BankTerminalWindow : FancyWindow
{
    public event Action<string, string>? OnSignInRequested;
    public event Action<string, string>? OnCreateAccountRequested;
    public event Action? OnSignOutRequested;
    public event Action<int>? OnBankSelected;
    public event Action<FixedPoint2>? OnWithdrawRequested;
    public event Action<string, FixedPoint2>? OnSendMoneyRequested;

    private int _selectedBankIndex = 0;

    public BankTerminalWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SendAmountInput.IsValid += text => float.TryParse(text, out var val) && val >= 0;
        WithdrawAmountInput.IsValid += text => float.TryParse(text, out var val) && val >= 0;

        // Sign In / Create Tab Sub-switching
        TabSignInMode.OnPressed += _ => SetAuthTab(true);
        TabCreateMode.OnPressed += _ => SetAuthTab(false);

        // Dropdown selection routing
        BankDropdown.OnItemSelected += args =>
        {
            _selectedBankIndex = args.Id;
            BankDropdown.SelectId(args.Id);
            OnBankSelected?.Invoke(args.Id);
        };

        // Hook operational trigger events
        ExecuteSignInButton.OnPressed += _ => OnSignInRequested?.Invoke(AuthAccountInput.Text, AuthPasswordInput.Text);
        ExecuteCreateButton.OnPressed += _ => OnCreateAccountRequested?.Invoke(AuthAccountInput.Text, AuthPasswordInput.Text);
        SignOutButton.OnPressed += _ =>
        {
            AuthScreen.Visible = true;
            DashboardScreen.Visible = false;

            OnSignOutRequested?.Invoke();
        };

        ExecuteWithdrawButton.OnPressed += _ => SubmitWithdrawal();
        ExecuteSendButton.OnPressed += _ => SubmitSend();
    }

    public void UpdateAvailableBanks(List<string> bankIds)
    {
        BankDropdown.Clear();

        if (bankIds.Count == 0)
        {
            BankDropdown.AddItem("No Banks Connected");
            BankDropdown.Disabled = true;
            _selectedBankIndex = 0;
            return;
        }

        BankDropdown.Disabled = false;
        for (var i = 0; i < bankIds.Count; i++)
        {
            BankDropdown.AddItem($"Bank Terminal: {bankIds[i]}", i);
        }

        if (_selectedBankIndex <= 0)
            _selectedBankIndex = 0;
        else if (_selectedBankIndex >= bankIds.Count)
            _selectedBankIndex = bankIds.Count - 1;

        BankDropdown.SelectId(_selectedBankIndex);
    }

    public void UpdateAccount(string account, string password, FixedPoint2 balance, NetEntity? bank, string bankId)
    {
        if (string.IsNullOrEmpty(account))
        {
            // Reset input values across authorization views
            AuthAccountInput.Text = string.Empty;
            AuthPasswordInput.Text = string.Empty;

            AuthScreen.Visible = true;
            DashboardScreen.Visible = false;
            return;
        }

        // Populate and shift to active account session view dashboard
        ActiveAccountLabel.Text = $"Account Active: {account}";
        ActiveBankLabel.Text = bank != null ? $"Connected Gateway Node: {bankId}" : "Connected Gateway Node: Standalone Ledger";
        AccountBalanceLabel.Text = $"Balance: ${balance:F2}";

        AuthScreen.Visible = false;
        DashboardScreen.Visible = true;
    }

    private void SetAuthTab(bool showSignIn)
    {
        TabSignInMode.Pressed = showSignIn;
        TabCreateMode.Pressed = !showSignIn;

        SignInActionBox.Visible = showSignIn;
        CreateAccountActionBox.Visible = !showSignIn;
    }

    private void SubmitWithdrawal()
    {
        if (!double.TryParse(WithdrawAmountInput.Text, out var parsedValue))
            return;

        OnWithdrawRequested?.Invoke(FixedPoint2.New(parsedValue));
        WithdrawAmountInput.Text = string.Empty;
    }

    private void SubmitSend()
    {
        if (string.IsNullOrWhiteSpace(SendTargetInput.Text))
            return;

        if (!double.TryParse(SendAmountInput.Text, out var parsedValue))
            return;

        OnSendMoneyRequested?.Invoke(SendTargetInput.Text, FixedPoint2.New(parsedValue));
        SendAmountInput.Text = string.Empty;
        SendTargetInput.Text = string.Empty;
    }
}
