using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Guidebook.Richtext;
using Content.Shared.Chemistry.Reaction;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding a reaction group into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideReagentReactionGroupEmbed : BoxContainer, IDocumentTag
{
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly ISawmill _sawmill = IoCManager.Resolve<ILogManager>().GetSawmill("guidebook");

    public GuideReagentReactionGroupEmbed()
    {
        _sawmill.Debug("Test1");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideReagentReactionGroupEmbed(string group) : this()
    {
        var prototypes = _prototype.EnumeratePrototypes<ReactionPrototype>()
            .Where(p => p.Group != null && p.Group.Equals(group))
            .OrderBy(p => p.Name);
        foreach (var reaction in prototypes)
        {
            var embed = new GuideReagentReaction(reaction, _prototype, IoCManager.Resolve<IEntitySystemManager>());
            GroupContainer.AddChild(embed);
        }
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Group", out var group))
        {
            _sawmill.Error("Reaction group embed tag is missing group argument");
            return false;
        }

        var prototypes = _prototype.EnumeratePrototypes<ReactionPrototype>()
            .Where(p => p.Group != null && p.Group.Equals(group))
            .OrderBy(p => p.Name);
        foreach (var reaction in prototypes)
        {
            var embed = new GuideReagentReaction(reaction, _prototype, IoCManager.Resolve<IEntitySystemManager>());
            GroupContainer.AddChild(embed);
        }

        control = this;
        return true;
    }
}
