# port-space-law
- type: guideEntry
  id: SpaceLaw
  name: guide-entry-space-law
  text: "/ServerInfo/Guidebook/Security/SpaceLaw.xml"
  children:
  - CrimeList

- type: guideEntry
  id: CrimeList
  name: guide-entry-crime-list
  text: "/ServerInfo/Guidebook/Security/CrimeList.xml"
