// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Shitcode.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ActionsTabControl : BaseTabControl
{
    public ActionsTabControl()
    {
        RobustXamlLoader.Load(this);
    }

    public override bool UpdateState() => true;
}
